import {DockingManager,LayoutRoot,LayoutPanel,LayoutDocumentPane,LayoutAnchorablePane,LayoutDocument,LayoutAnchorable} from '@wieslawsoltes/dockyard';
import dockCss from '@wieslawsoltes/dockyard/styles.css';
import {ObservableList,FlatTreeDataGridSource,TextColumn} from '@wieslawsoltes/treedatagridweb/core';
import '@wieslawsoltes/treedatagridweb/web';
import {SourceCache,toCollection} from '@wieslawsoltes/dynamicdataweb';
import '@wieslawsoltes/ribbon-web';
import {defineViewModel,reactiveProperty,WhenAnyValue} from '@wieslawsoltes/reactiveweb';
import {BindCommand} from '@wieslawsoltes/reactiveweb/html';
import {RBush,Envelope} from '@wieslawsoltes/rbushweb';
import {BidirectionalGraph,TaggedEdge,defineQuikGraphViewer} from '@wieslawsoltes/quikgraphweb';
/** Actual optional adapters, built against the companion packages. No replacement mocks. */
export async function attachCompanions({workbook,grid,commands,documentPane,inspector,workspace,ribbonHost}){
 const cleanup=[],style=document.createElement('style');style.textContent=dockCss;document.head.append(style);cleanup.push(()=>style.remove());
 const ribbon=document.createElement('ribbon-web');ribbon.setAttribute('theme',grid.Theme);ribbon.model={tabs:[{id:'home',header:'Home',groups:[{id:'history',header:'History',items:[['undo','Undo'],['redo','Redo']].map(([id,label])=>({id,label,type:'button',icon:id,command:commands[id]}))},{id:'file',header:'Workbook',items:[['open','Open'],['save','Save JSON'],['xlsx','Export XLSX'],['print','Print']].map(([id,label])=>({id,label,type:'button',icon:'save',size:'large',command:commands[id]}))},{id:'format',header:'Format',items:[['bold','Bold'],['italic','Italic'],['table','Table'],['conditional','Conditional format']].map(([id,label])=>({id,label,type:'button',icon:'grid',command:commands[id]}))}]},{id:'data',header:'Data',groups:[{id:'analysis',header:'Analysis',items:[['pivot','Pivot table'],['filter','Filter'],['sort','Sort'],['validation','Validation'],['goalSeek','Goal seek'],['functions','Functions']].map(([id,label])=>({id,label,type:'button',size:'large',command:commands[id]}))}]}]};ribbonHost.replaceChildren(ribbon);cleanup.push(()=>ribbon.remove());
 const cells=document.createElement('tree-data-grid');cells.style.cssText='display:block;height:100%;min-height:180px';cells.setAttribute('aria-label','Live workbook cells');let cellSource;
 const sourceCache=new SourceCache(row=>row.id);let scheduled=false,latest=[],disposed=false;
 const refreshCells=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;if(disposed)return;cellSource?.Dispose();cellSource=new FlatTreeDataGridSource(new ObservableList(latest.slice(0,1000)));cellSource.Columns.Add(new TextColumn('Sheet',x=>x.sheet,undefined,135));cellSource.Columns.Add(new TextColumn('Cell',x=>x.address,undefined,70));cellSource.Columns.Add(new TextColumn('Input',x=>x.input,(x,v)=>workbook.Worksheets.Get(x.sheet).GetCell(x.address).Input=v,'2*'));cellSource.Columns.Add(new TextColumn('Result',x=>x.display,undefined,'1*'));cells.Model=cellSource;});};
 const cacheSub=sourceCache.connect().pipe(toCollection()).subscribe(items=>{latest=Array.from(items);refreshCells();});cleanup.push(()=>{cacheSub.unsubscribe();sourceCache.dispose();cells.Dispose?.();cellSource?.Dispose();});
 const updateCache=()=>sourceCache.edit(cache=>{cache.clear();for(const sheet of workbook.Worksheets)for(const[n]of sheet._cells){const cell=sheet.GetCell(Math.floor(n/16384),n%16384);cache.addOrUpdate({id:sheet.Id+':'+cell.Address,sheet:sheet.Name,address:cell.Address,input:String(cell.Input??''),display:cell.Text});}});updateCache();
 defineQuikGraphViewer();const graphView=document.createElement('quikgraph-viewer');graphView.style.cssText='display:block;height:100%;min-height:180px';graphView.setAttribute('aria-label','Calculation dependency graph');const graphStatus=document.createElement('div'),graphPanel=document.createElement('div');graphPanel.style.cssText='height:100%;display:flex;flex-direction:column';graphStatus.style.cssText='padding:8px;font:11px system-ui';graphView.style.flex='1';graphPanel.append(graphStatus,graphView);
 const refreshGraph=()=>{const edges=workbook.Calculation.GetDependencyEdges(),graph=new BidirectionalGraph();graph.AddVerticesAndEdgeRange(edges.slice(0,1500).map(e=>new TaggedEdge(e.source,e.target,'depends on')));graphView.Graph=graph;graphView.Refresh();graphStatus.textContent=`${edges.length.toLocaleString()} cell dependency edges${edges.length>1500?' · first 1,500 displayed':''}. Range dependencies remain in the calculation engine.`;};refreshGraph();
 const index=new RBush();const onRender=e=>{index.Clear();index.BulkLoad(e.detail.charts.map((r,i)=>({...r,z:i,Envelope:new Envelope(r.x,r.y,r.x+r.width,r.y+r.height)})));};grid.addEventListener('grid-render',onRender);grid.ChartHitTest=(x,y)=>Array.from(index.Search(new Envelope(x,y,x,y))).sort((a,b)=>b.z-a.z);cleanup.push(()=>{grid.removeEventListener('grid-render',onRender);grid.ChartHitTest=null;index.Clear();});
 const VM=defineViewModel({properties:{Selection:reactiveProperty(grid.Selection),Status:reactiveProperty('Ready')},commands:{Calculate:{kind:'task',execute:async()=>{workbook.Calculate(true);}}}});const vm=new VM(),state=document.createElement('section');state.style.cssText='padding:16px;font:12px system-ui';const selected=document.createElement('div'),calculate=document.createElement('button');calculate.textContent='Recalculate workbook';calculate.style.cssText='margin:12px 0;padding:8px 12px;background:#107c41;color:white';state.append(selected,calculate);const selectionSub=WhenAnyValue(vm,'Selection').subscribe(value=>selected.textContent='Shared selection: '+value),binding=BindCommand(vm.Calculate,calculate),onSelection=e=>vm.Selection=e.detail.address;grid.addEventListener('selection-change',onSelection);cleanup.push(()=>{grid.removeEventListener('selection-change',onSelection);selectionSub.unsubscribe();if(typeof binding==='function')binding();else if(binding.Dispose)binding.Dispose();else binding.dispose?.();vm.Dispose?.();});
 const host=document.createElement('div');host.style.cssText='width:100%;height:100%;min-height:0';workspace.append(host);const manager=new DockingManager(host,{Theme:grid.Theme,Layout:new LayoutRoot({RootPanel:new LayoutPanel({Orientation:'Horizontal',Children:[new LayoutDocumentPane({Children:[new LayoutDocument({ContentId:'workbook',Title:workbook.Name,Content:documentPane}),new LayoutDocument({ContentId:'cells',Title:'Live cell inspector',Content:cells}),new LayoutDocument({ContentId:'graph',Title:'Formula dependencies',Content:graphPanel})]}),new LayoutAnchorablePane({DockWidth:270,Children:[new LayoutAnchorable({ContentId:'insights',Title:'Workbook insights',Content:inspector}),new LayoutAnchorable({ContentId:'reactive',Title:'Reactive commands',Content:state})]})]})})});
 const subscription=workbook.Changed.Subscribe(()=>{updateCache();refreshGraph();});cleanup.push(()=>subscription.Dispose());grid.Refresh();
 return{manager,ribbon,sourceCache,viewModel:vm,spatialIndex:index,Dispose(){if(disposed)return;disposed=true;for(const action of cleanup.toReversed())action();manager.Dispose();host.remove();workspace.append(documentPane,inspector);ribbonHost.replaceChildren();document.getElementById('ribbon').hidden=false;}};
}
