<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><EnableWindowsTargeting>true</EnableWindowsTargeting><PackageId>WieslawSoltes.GridWeb.Wpf</PackageId></PropertyGroup>
  <ItemGroup><ProjectReference Include="../GridWeb.Client/GridWeb.Client.csproj"/><PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50"/></ItemGroup>
</Project>
