import test from 'node:test';
import assert from 'node:assert/strict';
import {Workbook,GridViewModel,EventSource,RelayCommand,parseCell,parseRange,cellAddress,columnName,columnIndex,shiftFormula,FormulaError,AxisLayout,formatValue,parseDelimited,importDelimited,toDelimited,PivotTable,goalSeek,linearRegression,paginate,createPrintDocument,MAX_ROWS,MAX_COLUMNS} from '../src/core.js';
const setup=()=>{const book=new Workbook();return{book,sheet:book.ActiveWorksheet};};
const result=(s,f)=>{const v=s.Workbook.Calculation.Evaluate(f,{sheet:s});return v instanceof FormulaError?v.code:v;};
const formulas=[
 ['=1+2*3',7],['=(1+2)*3',9],['=2^3^2',64],['=-2^2',4],['=50%',.5],['="A"&"B"','AB'],['="a"="A"',true],['=1/0','#DIV/0!'],['=UNKNOWN(1)','#NAME?'],['=#N/A','#N/A'],
 ['=SUM(1,2,3)',6],['=SUM({1,2;3,4})',10],['=SUM("2",TRUE)',3],['=SUM({1,"2",TRUE})',1],['=PRODUCT(2,3,4)',24],['=AVERAGE(2,4,6)',4],['=MIN(4,2,-1)',-1],['=MAX(4,2,-1)',4],['=COUNT({1,2,"x",TRUE})',2],['=COUNTA({1,"x",TRUE})',3],['=COUNTBLANK({1,"",2})',1],['=SUMSQ(2,3)',13],['=MEDIAN(1,3,2,4)',2.5],['=LARGE({1,8,4},2)',4],['=SMALL({1,8,4},2)',4],['=STDEV.S(1,2,3)',1],['=VAR.S(1,2,3)',1],['=VAR.P(1,2,3)',2/3],['=STDEV.P(1,2,3)',Math.sqrt(2/3)],['=PERCENTILE.INC({1,2,3,4},0.5)',2.5],['=QUARTILE.INC({1,2,3,4},2)',2.5],['=RANK.EQ(3,{1,2,3,4})',2],
 ['=SUMIF({1,2,3},">1",{10,20,30})',50],['=COUNTIF({"West","East","west"},"w*")',2],['=AVERAGEIF({1,2,3},">1",{10,20,30})',25],['=SUMIFS({10,20,30},{1,2,3},">1",{"x","x","y"},"x")',20],['=COUNTIFS({1,2,3},">1",{"x","x","y"},"x")',1],['=AVERAGEIFS({10,20,30},{1,2,3},">1")',25],['=SUMPRODUCT({1,2,3},{4,5,6})',32],
 ['=ABS(-4)',4],['=SIGN(-3)',-1],['=INT(-1.2)',-2],['=TRUNC(-1.2)',-1],['=MOD(-3,2)',1],['=POWER(3,3)',27],['=SQRT(81)',9],['=SQRT(-1)','#NUM!'],['=ROUND(1.235,2)',1.24],['=ROUND(-1.5,0)',-2],['=ROUNDUP(-1.21,1)',-1.3],['=ROUNDDOWN(-1.29,1)',-1.2],['=CEILING.MATH(4.2)',5],['=FLOOR.MATH(4.8)',4],['=MROUND(10,3)',9],['=EVEN(3)',4],['=ODD(4)',5],['=FACT(5)',120],['=COMBIN(5,2)',10],['=GCD(24,36)',12],['=LCM(6,8)',24],['=QUOTIENT(7,3)',2],['=DEGREES(PI())',180],['=RADIANS(180)',Math.PI],['=SIN(0)',0],['=COS(0)',1],['=TAN(0)',0],['=ASIN(0)',0],['=ACOS(1)',0],['=ATAN(0)',0],['=EXP(0)',1],['=LN(1)',0],['=LOG10(100)',2],['=LOG(8,2)',3],
 ['=IF(TRUE,42,1/0)',42],['=IF(FALSE,1/0,42)',42],['=IFERROR(1/0,"fallback")','fallback'],['=IFNA(NA(),7)',7],['=IFNA(1/0,7)','#DIV/0!'],['=IFS(FALSE,1,TRUE,2)',2],['=SWITCH(2,1,"one",2,"two","other")','two'],['=AND(TRUE,1,2)',true],['=OR(FALSE,0,2)',true],['=NOT(0)',true],['=XOR(TRUE,TRUE)',false],['=ISERROR(1/0)',true],['=ISNA(NA())',true],['=ISNUMBER(42)',true],['=ISTEXT("42")',true],['=ISLOGICAL(TRUE)',true],['=ISEVEN(4)',true],['=ISODD(5)',true],['=N(TRUE)',1],['=T(12)',''],['=TYPE("x")',2],
 ['=LEN("hello")',5],['=LEFT("hello",2)','he'],['=RIGHT("hello",2)','lo'],['=MID("hello",2,3)','ell'],['=LOWER("AbC")','abc'],['=UPPER("AbC")','ABC'],['=PROPER("hello WORLD")','Hello World'],['=TRIM("  a  b  ")','a b'],['=CLEAN(CHAR(9)&"ok")','ok'],['=FIND("bc","abc")',2],['=SEARCH("BC","abc")',2],['=SUBSTITUTE("a-a-a","a","b",2)','a-b-a'],['=REPLACE("abcdef",2,3,"X")','aXef'],['=CONCAT("a",1,"b")','a1b'],['=CONCATENATE("a","b")','ab'],['=TEXTJOIN(",",TRUE,{"a","","b"})','a,b'],['=REPT("ab",3)','ababab'],['=EXACT("a","A")',false],['=VALUE("42.5")',42.5],['=CHAR(65)','A'],['=CODE("A")',65],['=UNICHAR(9733)','★'],['=UNICODE("★")',9733],['=TEXTBEFORE("a:b:c",":")','a'],['=TEXTAFTER("a:b:c",":")','b:c'],['=TEXTSPLIT("a,b;c,d",",",";")',[['a','b'],['c','d']]],
 ['=DATE(1900,1,1)',1],['=DATE(1900,2,28)',59],['=DATE(1900,2,29)',60],['=DATE(1900,3,1)',61],['=YEAR(DATE(2026,9,13))',2026],['=MONTH(DATE(2026,9,13))',9],['=DAY(60)',29],['=HOUR(TIME(14,30,0))',14],['=MINUTE(TIME(14,30,0))',30],['=SECOND(TIME(14,30,45))',45],['=DAYS(DATE(2026,9,13),DATE(2026,9,1))',12],['=WEEKDAY(DATE(2026,9,13),2)',7],['=EDATE(DATE(2024,1,31),1)',45351],['=EOMONTH(DATE(2024,1,1),1)',45351],['=NETWORKDAYS(DATE(2026,9,7),DATE(2026,9,11))',5],['=WORKDAY(DATE(2026,9,11),1)',46279],
 ['=PMT(0,10,100)',-10],['=PV(0,10,-10)',100],['=FV(0,10,-10)',100],['=NPER(0,-10,100)',10],['=NPV(0.1,110,121)',200],['=IRR({-100,110})',.1],['=SLN(1000,100,9)',100],['=SYD(1000,100,9,1)',180],
 ['=INDEX({1,2;3,4},2,1)',3],['=MATCH(3,{1,3,5},0)',2],['=XMATCH("B",{"a","b","c"})',2],['=XLOOKUP("B",{"a","b"},{10,20})',20],['=XLOOKUP("z",{"a","b"},{10,20},"missing")','missing'],['=VLOOKUP(2,{1,10;2,20;3,30},2,FALSE)',20],['=HLOOKUP(2,{1,2,3;10,20,30},2,FALSE)',20],['=CHOOSE(2,"a","b","c")','b'],
 ['=SEQUENCE(2,3)',[[1,2,3],[4,5,6]]],['=TRANSPOSE({1,2;3,4})',[[1,3],[2,4]]],['=FILTER({1,2;3,4},{FALSE;TRUE})',[[3,4]]],['=SORT({3,"c";1,"a";2,"b"})',[[1,'a'],[2,'b'],[3,'c']]],['=UNIQUE({1;2;1;3})',[[1],[2],[3]]],['=TAKE({1,2;3,4},1)',[[1,2]]],['=DROP({1,2;3,4},1)',[[3,4]]],['=CHOOSECOLS({1,2,3;4,5,6},3,1)',[[3,1],[6,4]]],['=CHOOSEROWS({1;2;3},3,1)',[[3],[1]]],['=VSTACK({1,2},{3,4})',[[1,2],[3,4]]],['=HSTACK({1;2},{3;4})',[[1,3],[2,4]]],['=TOCOL({1,2;3,4})',[[1],[2],[3],[4]]],['=TOROW({1,2;3,4})',[[1,2,3,4]]],['=LET(x,4,x*2)',8],['=MAP({1,2;3,4},LAMBDA(x,x^2))',[[1,4],[9,16]]],['=BYROW({1,2;3,4},LAMBDA(r,SUM(r)))',[[3],[7]]],['=BYCOL({1,2;3,4},LAMBDA(c,SUM(c)))',[[4,6]]],['=REDUCE(0,{1,2,3},LAMBDA(a,b,a+b))',6],['=SCAN(0,{1,2,3},LAMBDA(a,b,a+b))',[[1,3,6]]],['=ROWS(A:A)',1048576],['=COLUMNS(1:1)',16384],['=ADDRESS(2,3)','$C$2'],['=ADDRESS(2,3,4)','C2']
];
for(const[formula,expected]of formulas)test('formula '+formula,()=>{const{sheet}=setup();const actual=result(sheet,formula);if(typeof expected==='number')assert.ok(Math.abs(actual-expected)<Math.max(1e-8,Math.abs(expected)*1e-9),`${actual} != ${expected}`);else assert.deepEqual(actual,expected);});
test('all address columns round-trip and bounds',()=>{for(let c=0;c<MAX_COLUMNS;c++)assert.equal(columnIndex(columnName(c)),c);assert.equal(cellAddress(MAX_ROWS-1,MAX_COLUMNS-1),'XFD1048576');assert.throws(()=>parseCell('XFE1'));assert.throws(()=>parseCell('A1048577'));assert.deepEqual(parseRange("'A B'!$B$2:A1"),{sheet:'A B',r1:0,c1:0,r2:1,c2:1});});
test('formula copying preserves absolute references and quoted strings',()=>{assert.equal(shiftFormula('=SUM($A1,A$1,$A$1,"A1",Sheet1!B2)',2,3),'=SUM($A3,D$1,$A$1,"A1",\'Sheet1\'!E4)');assert.equal(shiftFormula('=A1',-1,0),'=#REF!');});
test('cross-sheet dependency invalidation and unrelated cache retention',()=>{const{book,sheet}=setup(),other=book.Worksheets.Add('Inputs');sheet.GetCell('A1').Formula='Inputs!B2*2';sheet.GetCell('A2').Formula='5*5';const before=book.Calculation.EvaluationCount;other.GetCell('B2').Value=4;assert.equal(sheet.GetCell('A1').Value,8);assert.equal(book.Calculation.EvaluationCount-before,1);other.Name="A ' B";assert.equal(sheet.GetCell('A1').Value,8);assert.equal(sheet.GetCell('A1').Formula,"='A '' B'!B2*2");});
test('range and whole-column dependencies notice newly populated cells',()=>{const{sheet}=setup();sheet.GetCell('B1').Formula='SUM(A:A)';sheet.GetCell('A100').Value=8;assert.equal(sheet.GetCell('B1').Value,8);sheet.GetCell('A100').Value=12;assert.equal(sheet.GetCell('B1').Value,12);});
test('blank counting on full columns is bounded',()=>{const{sheet}=setup();sheet.GetCell('A20').Value='x';sheet.GetCell('B1').Formula='COUNTBLANK(A:A)';assert.equal(sheet.GetCell('B1').Value,MAX_ROWS-1);});
test('circular references and unknown functions are error values',()=>{const{sheet}=setup();sheet.GetCell('A1').Formula='B1';sheet.GetCell('B1').Formula='A1';assert.equal(sheet.GetCell('A1').Value.code,'#CIRC!');sheet.GetCell('B1').Value=3;assert.equal(sheet.GetCell('A1').Value,3);});
test('lazy branch dependencies rewire after a condition changes',()=>{const{sheet}=setup();sheet.GetRange('A1:C1').Values=[[true,10,20]];sheet.GetCell('D1').Formula='IF(A1,B1,C1)';assert.equal(sheet.GetCell('D1').Value,10);sheet.GetCell('A1').Value=false;assert.equal(sheet.GetCell('D1').Value,20);sheet.GetCell('C1').Value=30;assert.equal(sheet.GetCell('D1').Value,30);});
test('dynamic spills recalculate consumers that were calculated before their anchor',()=>{const{book,sheet}=setup();book.Transaction('Populate',()=>{sheet.GetCell('D1').Formula='B2*10';sheet.GetCell('A1').Formula='SEQUENCE(2,2)';});assert.equal(sheet.GetCell('D1').Value,40);sheet.GetCell('A1').Formula='SEQUENCE(2,2,10)';assert.equal(sheet.GetCell('D1').Value,130);assert.throws(()=>sheet.GetCell('B2').Value=99,/spilled/);});
test('spill blocker, deletion and source resize',()=>{const{sheet}=setup();sheet.GetCell('B2').Value=9;sheet.GetCell('A1').Formula='SEQUENCE(2,2)';assert.equal(sheet.GetCell('A1').Value.code,'#SPILL!');sheet.GetCell('B2').Value=null;assert.equal(sheet.GetCell('B2').Value,4);sheet.GetCell('A1').Formula='SEQUENCE(1,2)';assert.equal(sheet.GetCell('B2').Value,null);assert.equal(result(sheet,'=SUM(A1#)'),3);});
test('transactions commit and undo one batch',()=>{const{book,sheet}=setup();book.Transaction('Two cells',()=>{sheet.GetCell('A1').Value=2;sheet.GetCell('B1').Formula='A1*3';});assert.equal(sheet.GetCell('B1').Value,6);assert.equal(book._history.length,1);book.Undo();assert.equal(sheet.CellCount,0);book.Redo();assert.equal(sheet.GetCell('B1').Value,6);});
test('failing transactions restore inputs and formula calculation',()=>{const{book,sheet}=setup();sheet.GetCell('A1').Value=3;sheet.GetCell('B1').Formula='A1*2';assert.throws(()=>book.Transaction('Bad',()=>{sheet.GetCell('A1').Value=7;sheet.GetCell('B2').Value=Infinity;}));assert.equal(sheet.GetCell('A1').Value,3);assert.equal(sheet.GetCell('B1').Value,6);});
test('validation rejects invalid paste atomically',()=>{const{sheet}=setup();sheet.AddValidation('A1:B2',{type:'whole',min:0,max:10});assert.throws(()=>sheet.GetRange('A1:B2').Values=[[1,2],[3,20]]);assert.deepEqual(sheet.GetRange('A1:B2').Values,[[null,null],[null,null]]);});
test('literal values do not execute formulas, Input does',()=>{const{sheet}=setup();sheet.GetCell('A1').Value='=1+1';assert.equal(sheet.GetCell('A1').Value,'=1+1');sheet.GetCell('A2').Input='=1+1';assert.equal(sheet.GetCell('A2').Value,2);sheet.GetCell('A3').Input="'=1+1";assert.equal(sheet.GetCell('A3').Value,'=1+1');});
test('named ranges and lambda calls',()=>{const{book,sheet}=setup();sheet.GetRange('A1:A2').Values=[[2],[3]];book.DefineName('Data','=Sheet1!A1:A2');book.DefineName('TimesThree','=LAMBDA(x,x*3)');assert.equal(result(sheet,'=SUM(Data)'),5);assert.equal(result(sheet,'=TimesThree(7)'),21);assert.throws(()=>book.DefineName('A1',4));});
test('structured table references follow changed headers and values',()=>{const{sheet}=setup();sheet.GetRange('A1:B3').Values=[['Item','Revenue'],['A',3],['B',4]];sheet.AddTable('A1:B3','Sales');sheet.GetCell('D1').Formula='SUM(Sales[Revenue])';assert.equal(sheet.GetCell('D1').Value,7);sheet.GetCell('B3').Value=8;assert.equal(sheet.GetCell('D1').Value,11);});
test('duplicate table headers normalized',()=>{const{sheet}=setup();sheet.GetRange('A1:C2').Values=[['Name','Name',null],[1,2,3]];sheet.AddTable('A1:C2','Data');assert.deepEqual(sheet.GetRange('A1:C1').Values,[['Name','Name2','Column3']]);});
test('insert rows updates ranges and cross-sheet references, undo restores identity',()=>{const{book,sheet}=setup();sheet.GetRange('A1:A3').Values=[[1],[2],[3]];const other=book.Worksheets.Add('Summary');other.GetCell('A1').Formula='SUM(Sheet1!A1:A3)';sheet.InsertRows(1);assert.equal(other.GetCell('A1').Formula,"=SUM('Sheet1'!A1:A4)");assert.equal(other.GetCell('A1').Value,6);book.Undo();assert.equal(other.GetCell('A1').Formula,'=SUM(Sheet1!A1:A3)');assert.equal(book.Worksheets.Get('Sheet1'),sheet);});
test('delete rows shrinks ranges and replaces deleted cell refs with REF',()=>{const{sheet}=setup();sheet.GetRange('A1:A3').Values=[[1],[2],[3]];sheet.GetCell('C5').Formula='SUM(A1:A3)';sheet.GetCell('D5').Formula='A2';sheet.DeleteRows(1);assert.equal(sheet.GetCell('C4').Formula,'=SUM(A1:A2)');assert.equal(sheet.GetCell('C4').Value,4);assert.equal(sheet.GetCell('D4').Value.code,'#REF!');});
test('insert at worksheet boundary does not discard values',()=>{const{sheet}=setup();sheet.GetCell('XFD1048576').Value='last';assert.throws(()=>sheet.InsertRows(0));assert.throws(()=>sheet.InsertColumns(0));});
test('overlapping copy has snapshot semantics',()=>{const{sheet}=setup();sheet.GetRange('A1:A3').Values=[[1],[2],[3]];sheet.GetRange('A2:A4').CopyFrom(sheet.GetRange('A1:A3'),'values');assert.deepEqual(sheet.GetRange('A1:A4').Values,[[1],[1],[2],[3]]);});
test('copy formulas translates relative references',()=>{const{sheet}=setup();sheet.GetCell('A1').Value=2;sheet.GetCell('B1').Formula='A1+$A$1';sheet.GetRange('B2:B3').CopyFrom(sheet.GetRange('B1'));assert.equal(sheet.GetCell('B3').Formula,'=A3+$A$1');});
test('stable sorting preserves formulas and record styles',()=>{const{sheet}=setup();sheet.GetRange('A1:B4').Values=[['Name','Qty'],['C',3],['A',1],['B',2]];sheet.GetRange('C2:C4').Formulas=[['=B2*2'],['=B3*2'],['=B4*2']];sheet.GetRange('A1:C4').Sort([{column:0}]);assert.deepEqual(sheet.GetRange('A2:C4').Values,[['A',1,2],['B',2,4],['C',3,6]]);sheet.GetRange('A1:C4').Sort([{column:1,ascending:false}]);assert.equal(sheet.GetCell('A2').Value,'C');});
test('remove duplicates preserves formulas and is undoable',()=>{const{book,sheet}=setup();sheet.GetRange('A1:B4').Values=[['Name','Qty'],['A',2],['A',2],['B',3]];sheet.GetRange('C2:C4').Formulas=[['=B2*2'],['=B3*2'],['=B4*2']];const count=sheet.GetRange('A1:C4').RemoveDuplicates([0,1]);assert.equal(count,1);assert.equal(sheet.GetCell('C3').Formula,'=B3*2');assert.equal(sheet.GetCell('C3').Value,6);book.Undo();assert.equal(sheet.GetCell('A4').Value,'B');});
test('filter excludes rows from subtotal and updates on data edit',()=>{const{sheet}=setup();sheet.GetRange('A1:B4').Values=[['Item','Qty'],['A',1],['B',2],['C',3]];sheet.GetCell('D1').Formula='SUBTOTAL(9,B2:B4)';sheet.SetFilter('A1:B4',[{column:1,value:'>1'}]);assert.equal(sheet.GetCell('D1').Value,5);sheet.GetCell('B2').Value=4;assert.equal(sheet.GetCell('D1').Value,9);sheet.ClearFilter();assert.equal(sheet.GetCell('D1').Value,9);});
test('sheet protection and unlocked cells',()=>{const{sheet}=setup();sheet.GetCell('A1').Style={locked:false};sheet.Protect();assert.throws(()=>sheet.GetCell('B1').Value=1);sheet.GetCell('A1').Value=2;assert.equal(sheet.GetCell('A1').Value,2);assert.throws(()=>sheet.AddTable('A3:B4'));sheet.Unprotect();sheet.GetCell('B1').Value=3;});
test('JSON roundtrip preserves styles, formulas, comments and validation',()=>{const{book,sheet}=setup();sheet.GetCell('A1').Value=2;sheet.GetCell('B1').Formula='A1*3';sheet.GetCell('B1').Style={font:{bold:true},numberFormat:'$0.00'};sheet.GetCell('B1').Comment='note';sheet.AddValidation('A1',{type:'whole',min:0,max:9});const loaded=Workbook.FromJSON(JSON.stringify(book.ToJSON()));assert.equal(loaded.ActiveWorksheet.GetCell('B1').Text,'$6.00');assert.equal(loaded.ActiveWorksheet.GetCell('B1').Comment,'note');assert.throws(()=>loaded.ActiveWorksheet.GetCell('A1').Value=10);});
test('unsafe JSON versions, prototype keys and excessive ranges fail',()=>{assert.throws(()=>Workbook.FromJSON({format:'Other',version:1,sheets:[]}));const{sheet}=setup();assert.throws(()=>sheet.GetRange('A:XFD').Values);assert.throws(()=>sheet.GetCell('A1').Value={__proto__:null,x:1});});
test('events and MVVM command disposal',()=>{const event=new EventSource();let calls=0;const s=event.Subscribe(()=>calls++);event.Emit(1);s.Dispose();s.Dispose();event.Emit(2);assert.equal(calls,1);const{book,sheet}=setup(),vm=new GridViewModel(book);assert.equal(vm.Undo.CanExecute(),false);sheet.GetCell('A1').Value=1;assert.equal(vm.Undo.CanExecute(),true);vm.Undo.Execute();assert.equal(sheet.GetCell('A1').Value,null);vm.Dispose();assert.equal(book.Changed.Count,0);});
test('sparse Fenwick layout matches dense prefix sums',()=>{const a=new AxisLayout(1000,24),dense=Array(1000).fill(24);for(let i=0;i<1000;i+=7){a.SetSize(i,i%5===0?0:30);dense[i]=i%5===0?0:30;}let sum=0;for(let i=0;i<1000;i++){assert.equal(a.Offset(i),sum);if(dense[i])assert.equal(a.IndexAt(sum+.1),i);sum+=dense[i];}assert.equal(a.TotalSize,sum);});
test('pagination, repeated headers, hidden rows and escaped HTML',()=>{const{sheet}=setup();sheet.GetRange('A1:B100').Values=Array.from({length:100},(_,i)=>[i,'<script>alert(1)</script>']);sheet.HideRows(1,1);const pages=paginate(sheet,{repeatRows:1});assert.ok(pages.pages.length>1);assert.ok(pages.pages.every(p=>p.rows.includes(0)&&!p.rows.includes(1)));const html=createPrintDocument(sheet);assert.ok(!html.includes('<script>alert'));assert.ok(html.includes('&lt;script&gt;'));});
test('CSV parser, escaping and formula injection policy',()=>{assert.deepEqual(parseDelimited('"a,b","line\n2"\r\n3,"a""b"'),[['a,b','line\n2'],['3','a"b']]);assert.throws(()=>parseDelimited('"unfinished'));const{sheet}=setup();importDelimited(sheet,'=1+2,12');assert.equal(sheet.GetCell('A1').Value,'=1+2');assert.equal(sheet.GetCell('B1').Value,12);assert.ok(toDelimited(sheet.UsedRange).startsWith("'=1+2"));});
test('pivot aggregation by row and column',()=>{const{sheet}=setup();sheet.GetRange('A1:C5').Values=[['Team','Q','Value'],['A','Q1',2],['A','Q2',3],['B','Q1',4],['A','Q1',5]];const p=new PivotTable(sheet.UsedRange,{rows:['Team'],columns:['Q'],values:[{column:'Value',aggregate:'sum',name:'Total'}]});assert.deepEqual(p.Result,[['Team','Q1 / Total','Q2 / Total'],['A',7,3],['B',4,0]]);});
test('goal seek commits once and restores on failure',()=>{const{book,sheet}=setup();sheet.GetCell('A1').Value=2;sheet.GetCell('B1').Formula='A1*3+2';book.ClearHistory();const solved=goalSeek(sheet.GetCell('B1'),sheet.GetCell('A1'),17);assert.ok(Math.abs(solved.value-5)<1e-6);assert.equal(book._history.length,1);book.Undo();assert.equal(sheet.GetCell('A1').Value,2);sheet.GetCell('B1').Formula='1/0';assert.throws(()=>goalSeek(sheet.GetCell('B1'),sheet.GetCell('A1'),17));assert.equal(sheet.GetCell('A1').Value,2);});
test('linear regression',()=>{const r=linearRegression([1,2,3],[3,5,7]);assert.equal(r.slope,2);assert.equal(r.intercept,1);assert.equal(r.rSquared,1);assert.equal(r.predict(4),9);});
test('read-your-writes within an atomic transaction',()=>{const{book,sheet}=setup();sheet.GetCell('A1').Value=1;sheet.GetCell('B1').Formula='A1*2';book.Transaction(()=>{sheet.GetCell('A1').Value=7;assert.equal(sheet.GetCell('B1').Value,14);sheet.GetCell('C1').Value=sheet.GetCell('B1').Value+1;});assert.equal(sheet.GetCell('C1').Value,15);});
test('custom validation reads the proposed value',()=>{const{sheet}=setup();sheet.AddValidation('A1:A10',{type:'custom',formula:'=A1>=10'});sheet.GetCell('A2').Value=12;assert.throws(()=>sheet.GetCell('A2').Value=3);assert.equal(sheet.GetCell('A2').Value,12);});
test('partial spill clear rejected; anchor clear clears the spill',()=>{const{sheet}=setup();sheet.GetCell('A1').Formula='SEQUENCE(2,2)';assert.throws(()=>sheet.GetRange('B2').Clear('contents'));sheet.GetRange('A1').Clear('contents');assert.equal(sheet.GetCell('B2').Value,null);});
test('autofill continuation outside source and undo is a single edit',()=>{const{book,sheet}=setup();sheet.GetRange('A1:A2').Values=[[2],[4]];book.ClearHistory();sheet.GetRange('A1:A2').AutoFill('A3:A5');assert.deepEqual(sheet.GetRange('A3:A5').Values,[[6],[8],[10]]);assert.equal(book._history.length,1);book.Undo();assert.equal(sheet.GetCell('A3').Value,null);});
test('COUNTBLANK includes spilled values',()=>{const{sheet}=setup();sheet.GetCell('A1').Formula='SEQUENCE(3,1)';sheet.GetCell('C1').Formula='COUNTBLANK(A1:A5)';assert.equal(sheet.GetCell('C1').Value,2);});
test('cannot remove a worksheet belonging to another workbook',()=>{const{book}=setup(),other=new Workbook();book.Worksheets.Add('Second');assert.throws(()=>book.Worksheets.Remove(other.ActiveWorksheet));assert.equal(book.Worksheets.Count,2);});
test('whole-column and whole-row references translate and rename',()=>{const{book,sheet}=setup();sheet.GetCell('A1').Value=5;const other=book.Worksheets.Add('Other');other.GetCell('A1').Formula='SUM(Sheet1!A:A)';sheet.InsertColumns(0);assert.equal(other.GetCell('A1').Formula,"=SUM('Sheet1'!B:B)");assert.equal(other.GetCell('A1').Value,5);sheet.Name='Data rows';assert.equal(other.GetCell('A1').Formula,"=SUM('Data rows'!B:B)");sheet.InsertRows(0);assert.equal(other.GetCell('A1').Value,5);assert.equal(shiftFormula('=SUM(A:B)+SUM($3:4)+LEN("A:B")',2,1),'=SUM(B:C)+SUM($3:6)+LEN("A:B")');});
test('spill extents belong to the used range and shrink on recalculation',()=>{const{book,sheet}=setup();sheet.GetCell('D3').Formula='SEQUENCE(8,4)';assert.equal(sheet.UsedRange.Address,'D3:G10');sheet.GetCell('D3').Formula='SEQUENCE(2,2)';assert.equal(sheet.UsedRange.Address,'D3:E4');book.Undo();assert.equal(sheet.UsedRange.Address,'D3:G10');});
test('filtered subtotals survive JSON round trip',()=>{const{book,sheet}=setup();sheet.GetRange('A1:B4').Values=[['X','Y'],['A',1],['B',5],['A',3]];sheet.GetCell('C1').Formula='SUBTOTAL(9,B2:B4)';sheet.SetFilter('A1:B4',[{column:0,value:'A'}]);const clone=Workbook.FromJSON(book.ToJSON());assert.equal(clone.ActiveWorksheet.GetCell('C1').Value,4);});
