import test from 'node:test';import assert from 'node:assert/strict';import {deflateRawSync} from 'node:zlib';
import {Workbook} from '../src/core.js';import {exportXlsx,importXlsx} from '../src/io.js';import {writeZip,readZip,crc32} from '../src/zip.js';import {parseXML,xmlEscape,xmlDecode,descendants} from '../src/xml.js';import {createShowcase} from '../demo/fixtures.js';
const dec=new TextDecoder(),enc=new TextEncoder();
async function unpack(bytes){const map=await readZip(bytes);return Object.fromEntries([...map].map(([k,v])=>[k,dec.decode(v)]));}
test('XLSX simple typed values, literal formula strings and formulas',async()=>{const b=new Workbook(),s=b.ActiveWorksheet;s.GetRange('A1:D2').Values=[['=1+2','hello & < > "',true,42],[null,'line\n2',false,-1.5]];s.GetCell('E1').Formula='D1*2';const {workbook,warnings}=await importXlsx(exportXlsx(b));assert.deepEqual(warnings,[]);assert.deepEqual(workbook.ActiveWorksheet.GetRange('A1:E2').Values,[['=1+2','hello & < > "',true,42,84],[null,'line\n2',false,-1.5,null]]);assert.equal(workbook.ActiveWorksheet.GetCell('E1').Formula,'=D1*2');});
test('XLSX showcase contains real parts and round-trips all sample formulas',async()=>{const b=createShowcase(),bytes=exportXlsx(b),files=await unpack(bytes);assert.ok(files['xl/charts/chart1.xml']);assert.ok(files['xl/tables/table1.xml']);assert.ok(files['xl/comments1.xml']);assert.ok(files['xl/drawings/drawing1.xml']);assert.ok(files['[Content_Types].xml']);for(const[path,content]of Object.entries(files))if(path.endsWith('.xml'))assert.doesNotThrow(()=>parseXML(content),path);const loaded=await importXlsx(bytes);assert.equal(loaded.workbook.Worksheets.Count,5);assert.equal(loaded.workbook.Worksheets.Get('Operating plan').GetCell('C19').Value,1519700);assert.equal(loaded.workbook.Worksheets.Get('Formula lab').GetCell('B5').Value,42);assert.equal(loaded.workbook.Worksheets.Get('Formula lab').GetCell('D22').Value,24);assert.equal(loaded.workbook.Worksheets.Get('Operating plan').Charts.length,1);assert.equal(loaded.workbook.Worksheets.Get('Pivot summary').Charts.length,1);assert.deepEqual(loaded.warnings,[]);});
test('XLSX fonts, fills, borders and custom formats',async()=>{const b=new Workbook(),s=b.ActiveWorksheet;s.GetCell('A1').Value=1.25;s.GetCell('A1').Style={font:{bold:true,italic:true,underline:true,color:'#123456',size:14,name:'Arial'},fill:'#ddeeff',numberFormat:'0.00%',wrapText:true,horizontalAlignment:'center',border:true,locked:false};const {workbook}=await importXlsx(exportXlsx(b));const c=workbook.ActiveWorksheet.GetCell('A1');assert.equal(c.Text,'125.00%');assert.equal(c.Style.font.bold,true);assert.equal(c.Style.font.color.toLowerCase(),'#123456');assert.equal(c.Style.fill.toLowerCase(),'#ddeeff');assert.equal(c.Style.wrapText,true);assert.equal(c.Style.horizontalAlignment,'center');assert.equal(c.Style.locked,false);});
test('XLSX notes, merged cells, dimensions, frozen panes and print settings',async()=>{const b=new Workbook(),s=b.ActiveWorksheet;s.GetCell('A1').Value='Title';s.GetCell('A1').Comment='A note & details';s.GetRange('A1:B2').Merge();s.SetRowHeight(0,40);s.SetColumnWidth(0,180);s.HideRows(3);s.FreezePanes(2,1);s._setMeta('print',{paper:'Letter',orientation:'portrait',scale:.8,repeatRows:2,area:s.GetRange('A1:D10').Bounds});const{workbook}=await importXlsx(exportXlsx(b)),r=workbook.ActiveWorksheet;assert.equal(r.GetCell('A1').Comment,'A note & details');assert.equal(r.MergedRanges.length,1);assert.equal(r._meta.rows[0].size,40);assert.ok(Math.abs(r._meta.columns[0].size-180)<.01);assert.equal(r._meta.rows[3].hidden,true);assert.equal(r.FrozenRows,2);assert.equal(r.FrozenColumns,1);assert.equal(r._meta.print.paper,'Letter');assert.equal(r._meta.print.scale,.8);assert.deepEqual(r._meta.print.area,s._meta.print.area);});
test('XLSX validations and conditional rules persist',async()=>{const b=new Workbook(),s=b.ActiveWorksheet;s.AddValidation('A1:A9',{type:'list',values:['A','B']});s.AddValidation('B1:B9',{type:'whole',min:0,max:10});s.AddConditionalFormat('C1:C9',{type:'cellValue',operator:'lessThan',value:0,style:{fill:'#ffeeee'}});s.AddConditionalFormat('D1:D9',{type:'dataBar',color:'#00aa00'});const{workbook}=await importXlsx(exportXlsx(b)),r=workbook.ActiveWorksheet;assert.equal(r._meta.validations.length,2);assert.throws(()=>r.GetCell('A2').Value='Other');assert.throws(()=>r.GetCell('B2').Value=20);assert.equal(r._meta.conditionalFormats.length,2);assert.equal(r._meta.conditionalFormats[0].operator,'lessThan');});
for(const type of ['column','bar','line','area','pie','scatter'])test('XLSX '+type+' chart',async()=>{const b=new Workbook(),s=b.ActiveWorksheet;s.GetRange('A1:C4').Values=[['X','Y','Z'],[1,3,5],[2,4,6],[3,5,7]];s.AddChart('A1:C4',{type,title:'Example & '+type,row:6,column:4,width:450,height:250});const{workbook,warnings}=await importXlsx(exportXlsx(b));assert.equal(workbook.ActiveWorksheet.Charts[0].type,type);assert.equal(workbook.ActiveWorksheet.Charts[0].title,'Example & '+type);assert.equal(workbook.ActiveWorksheet.Charts[0].row,6);assert.deepEqual(warnings,[]);});
test('XLSX shared strings and shared formulas from external-style parts',async()=>{const b=new Workbook();b.ActiveWorksheet.GetRange('A1:B2').Values=[[2,4],[3,6]];const files=await unpack(exportXlsx(b));files['xl/sharedStrings.xml']='<?xml version="1.0"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><si><r><t>Hello</t></r><r><t> world</t></r></si></sst>';files['xl/_rels/workbook.xml.rels']=files['xl/_rels/workbook.xml.rels'].replace('</Relationships>','<Relationship Id="shared" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/></Relationships>');files['xl/worksheets/sheet1.xml']=files['xl/worksheets/sheet1.xml'].replace(/<c r="B1"[^>]*>.*?<\/c>/,'<c r="B1"><f t="shared" si="0" ref="B1:B2">A1*2</f><v>4</v></c>').replace(/<c r="B2"[^>]*>.*?<\/c>/,'<c r="B2"><f t="shared" si="0"/><v>6</v></c>').replace('</sheetData>','<row r="3"><c r="A3" t="s"><v>0</v></c></row></sheetData>');const{workbook}=await importXlsx(writeZip(files));assert.equal(workbook.ActiveWorksheet.GetCell('A3').Value,'Hello world');assert.equal(workbook.ActiveWorksheet.GetCell('B2').Formula,'=A2*2');assert.equal(workbook.ActiveWorksheet.GetCell('B2').Value,6);});
test('1904 date-system files fail explicitly rather than silently shift dates',async()=>{const files=await unpack(exportXlsx(new Workbook()));files['xl/workbook.xml']=files['xl/workbook.xml'].replace('<workbookPr date1904="0"/>','<workbookPr date1904="1"/>');await assert.rejects(()=>importXlsx(writeZip(files)),/1904/);});
test('unsupported parts produce import warnings',async()=>{const files=await unpack(exportXlsx(new Workbook()));files['xl/vbaProject.bin']='not executed';files['xl/connections.xml']='<connections/>';const result=await importXlsx(writeZip(files));assert.ok(result.warnings.length>=2);});
test('stored ZIP Unicode names and CRC round-trip',async()=>{const archive=writeZip({'folder/α.txt':'Hello 世界','empty':''});const files=await readZip(archive);assert.equal(dec.decode(files.get('folder/α.txt')),'Hello 世界');assert.equal(files.get('empty').length,0);assert.equal(crc32(enc.encode('123456789')),0xcbf43926);});
test('deflated ZIP entries decode with bounded output',async()=>{const input=enc.encode('Compressed test data '.repeat(50)),name=enc.encode('data.txt'),z=writeZip({'data.txt':input}),payload=deflateRawSync(input),local=z.slice(0,30+name.length),central=z.slice(30+name.length+input.length,z.length-22),end=z.slice(z.length-22);new DataView(local.buffer).setUint16(8,8,true);new DataView(local.buffer).setUint32(18,payload.length,true);new DataView(central.buffer).setUint16(10,8,true);new DataView(central.buffer).setUint32(20,payload.length,true);new DataView(end.buffer).setUint32(16,local.length+payload.length,true);const all=new Uint8Array([...local,...payload,...central,...end]);const files=await readZip(all);assert.deepEqual(files.get('data.txt'),input);});
test('CRC mismatch, truncated and unsafe ZIP archives are rejected',async()=>{const z=writeZip({'a.txt':'abc'});const corrupt=z.slice();corrupt[35]^=1;await assert.rejects(()=>readZip(corrupt),/CRC|integrity|checksum/i);await assert.rejects(()=>readZip(z.slice(0,-10)));assert.throws(()=>writeZip({'../secret':'x'}));const encrypted=z.slice(),view=new DataView(encrypted.buffer);view.setUint16(6,1,true);const central=38;view.setUint16(central+8,1,true);await assert.rejects(()=>readZip(encrypted),/encrypt/i);});
test('XML parser rejects DTD, mismatches and multiple roots',()=>{assert.throws(()=>parseXML('<!DOCTYPE x [<!ENTITY x SYSTEM "file:///secret">]><x>&x;</x>'));assert.throws(()=>parseXML('<a><b></a>'));assert.throws(()=>parseXML('<a/><b/>'));assert.equal(xmlDecode(xmlEscape('<>&"\'')),'<>&"\'');});
test('XML quoted greater-than and mixed-content order are preserved',async()=>{const{parseXML,allText}=await import('../src/xml.js');const n=parseXML('<a label="a > b">first<b>middle</b>last<![CDATA[!]]></a>');assert.equal(n.attrs.label,'a > b');assert.equal(allText(n),'firstmiddlelast!');});
test('XML malformed attributes/entities and trailing markup are rejected',async()=>{const{parseXML}=await import('../src/xml.js');for(const xml of ['<a flag/>','<a x="1"x="2"/>','<a>&unknown;</a>','<a>&#0;</a>','<a/>garbage','<a x="<"/>','<a/><'])assert.throws(()=>parseXML(xml),xml);});
