import test from 'node:test';import assert from 'node:assert/strict';
import {Workbook} from '../src/core.js';import {summarizePivot} from '../src/pivots/aggregate.js';import {exportXlsx,importXlsx} from '../src/io.js';import {readZip} from '../src/zip.js';import {parseXML,child,children} from '../src/xml.js';
import {applyDocument,diffDocuments} from '../src/collaboration/document.js';
const matrix=[['Region','Product','Revenue'],['North','A',10],['North','B',20],['South','A',30],['south','B',40]];
function sample(options={}){const book=new Workbook(),source=book.ActiveWorksheet;source.Name='Data';source.GetRange('A1:C5').Values=matrix;const sheet=book.Worksheets.Add('Pivot');book.ClearHistory();const pivot=book.PivotTables.Add('SalesPivot',source.GetRange('A1:C5'),sheet.GetRange('A1'),{rows:['Region'],values:[{column:'Revenue',aggregate:'sum',name:'Revenue'}],...options});return {book,source,sheet,pivot};}
test('managed pivots compute typed grouping and persist in the workbook',()=>{const {book,pivot}=sample();assert.deepEqual(pivot.OutputRange.Values,[['Region','Revenue'],['North',30],['South',70]]);const b=Workbook.FromJSON(JSON.stringify(book.ToJSON()));assert.equal(b.PivotTables.Count,1);assert.deepEqual(b.PivotTables.Get('SalesPivot').Refresh(),pivot.Refresh());});
test('creating and refreshing a managed pivot are atomic undoable operations',()=>{const {book,pivot,sheet,source}=sample();assert.equal(book._history.length,1);book.Undo();assert.equal(book.PivotTables.Count,0);assert.equal(sheet.GetCell('A1').Value,null);book.Redo();source.GetCell('C2').Value=15;assert.equal(pivot.IsStale,true);pivot.Refresh();assert.equal(sheet.GetCell('B2').Value,35);book.Undo();assert.equal(sheet.GetCell('B2').Value,30);});
test('row and column totals aggregate original rows, not already averaged summaries',()=>{const {pivot}=sample({columns:['Product'],rowGrandTotals:true,columnGrandTotals:true,values:[{column:'Revenue',aggregate:'average',name:'Mean'}]});assert.deepEqual(pivot.OutputRange.Values,[['Region','A / Mean','B / Mean','Grand Total / Mean'],['North',10,20,15],['South',30,40,35],['Grand Total',20,30,25]]);});
test('reconfiguration, filters and drill-down use the shared source',()=>{const {pivot}=sample();pivot.SetFilter('Region',['North']);assert.deepEqual(pivot.OutputRange.Values,[['Region','Revenue'],['North',30]]);assert.deepEqual(pivot.DrillDown(1,1),matrix.slice(0,3));pivot.SetFilter('Region',null);assert.equal(pivot.OutputRange.RowCount,3);assert.throws(()=>pivot.DrillDown(1,0));assert.throws(()=>pivot.DrillDown(1,1,{limit:1}));});
test('refresh clears stale rows when groups disappear',()=>{const {source,pivot,sheet}=sample();source.GetRange('A4:A5').Values=[['North'],['North']];pivot.Refresh();assert.equal(sheet.GetCell('A3').Value,null);assert.equal(sheet.GetCell('B2').Value,100);});
test('growth, source and pivot overlaps fail without corrupting other cells',()=>{const {book,source,pivot,sheet}=sample();source.GetCell('A5').Value='West';sheet.GetCell('A4').Value='do not overwrite';assert.throws(()=>pivot.Refresh(),/occupied/);assert.equal(sheet.GetCell('A4').Value,'do not overwrite');assert.throws(()=>book.PivotTables.Add('Bad',source.UsedRange,source.GetRange('B2')),/source/);assert.equal(book.PivotTables.Count,1);});
test('column/row inserts translate pivot source and destination with undo',()=>{const {book,source,sheet,pivot}=sample();source.InsertRows(0);assert.equal(pivot.Source.Address,'A2:C6');pivot.Refresh();sheet.InsertRows(0,2);assert.equal(pivot.Destination.Address,'A3');assert.equal(pivot.OutputRange.Address,'A3:B5');book.Undo();assert.equal(pivot.Destination.Address,'A1');source.InsertColumns(0);assert.equal(pivot.Source.Address,'B2:D6');pivot.Refresh();assert.equal(sheet.GetCell('B2').Value,30);});
test('renaming sheets retains stable IDs; deleting sources requires reconfiguration',()=>{const {book,source,pivot}=sample();source.Name='Renamed';assert.equal(pivot.Source.Worksheet.Name,'Renamed');book.Worksheets.Remove(source);assert.throws(()=>pivot.Refresh(),/removed/);const round=Workbook.FromJSON(book.ToJSON());assert.match(round.PivotTables.Get(0).InvalidReason,/removed/);book.Undo();pivot.Refresh();});
test('duplicate names, invalid headers and unsupported aggregates are rejected',()=>{const {book,source,sheet}=sample();assert.throws(()=>book.PivotTables.Add('SalesPivot',source.UsedRange,sheet.GetRange('H1')),/Duplicate/);assert.throws(()=>book.PivotTables.Add('Bad',source.UsedRange,sheet.GetRange('H1'),{values:[{column:2,aggregate:'pretend'}]}),/aggregate/);assert.throws(()=>summarizePivot([['A','a'],[1,2]],{}),/unique/);assert.throws(()=>summarizePivot([['A',''],[1,2]],{}),/headers/);});
for(const [aggregate,expected]of [['sum',10],['count',4],['countNumbers',4],['average',2.5],['min',1],['max',4],['product',24],['distinct',4],['variance',5/3],['variancePopulation',1.25],['standardDeviation',Math.sqrt(5/3)],['standardDeviationPopulation',Math.sqrt(1.25)]])test('pivot aggregate '+aggregate,()=>{const result=summarizePivot([['Group','Value'],...Array.from({length:4},(_,i)=>['A',i+1])],{rows:[0],values:[{column:1,aggregate}]}).result;assert.equal(result[1][1],expected);});
test('native export generates connected pivot definitions and typed cache records',async()=>{const {book,pivot}=sample({columnGrandTotals:true});const before=book.ToJSON(),revision=book.Revision,bytes=exportXlsx(book),parts=await readZip(bytes),xml=p=>parseXML(new TextDecoder().decode(parts.get(p)));assert.deepEqual(book.ToJSON(),before);assert.equal(book.Revision,revision);assert.equal(xml('xl/pivotTables/pivotTable1.xml').attrs.name,'SalesPivot');assert.equal(xml('xl/pivotCache/pivotCacheRecords1.xml').attrs.count,'4');assert.equal(children(child(xml('xl/pivotCache/pivotCacheDefinition1.xml'),'cacheFields'),'cacheField').length,3);assert.ok(new TextDecoder().decode(parts.get('xl/worksheets/_rels/sheet2.xml.rels')).includes('/pivotTable'));const imported=await importXlsx(bytes);assert.equal(imported.workbook.PivotTables.Count,1);assert.deepEqual(imported.workbook.PivotTables.Get(0).Refresh(),pivot.Refresh());});
test('native row filters and multiple measures survive a package round trip',async()=>{const {book,pivot}=sample({filters:[{column:'Region',values:['North']}],values:[{column:2,aggregate:'sum',name:'Sales'},{column:2,aggregate:'count',name:'Records'}]});const result=await importXlsx(exportXlsx(book));assert.deepEqual(result.workbook.PivotTables.Get(0).Refresh(),pivot.Refresh());});
test('unsupported native layouts require explicit flattening',async()=>{const {book}=sample({columns:['Product']});assert.throws(()=>exportXlsx(book),/flatten/);const b=await importXlsx(exportXlsx(book,{pivots:'flatten'}));assert.equal(b.workbook.PivotTables.Count,0);});
test('coauthoring treats pivot definitions as structure and retains them on apply',()=>{const {book}=sample(),empty=new Workbook();const before=empty.ToJSON();assert.equal(diffDocuments(before,book.ToJSON()).kind,'replace');applyDocument(empty,book.ToJSON());assert.equal(empty.PivotTables.Count,1);empty.PivotTables.Get(0).Refresh();});

test('grand totals with no row axes do not duplicate the aggregate result',()=>{const x=summarizePivot([['V'],[10],[20]],{rows:[],values:[{column:0,aggregate:'sum'}],columnGrandTotals:true});assert.deepEqual(x.result,[['sum of V'],[30]]);});
test('drill-down refuses stale row identities until refresh',()=>{const {pivot,source}=sample();source.GetCell('A2').Value='Ahead';assert.throws(()=>pivot.DrillDown(1,1),/Refresh/);pivot.Refresh();assert.equal(pivot.DrillDown(1,1)[1][0],'Ahead');});
test('flattened native-unsupported layouts refresh snapshots without modifying the view',async()=>{const {book,pivot,source,sheet}=sample({columns:['Product']});source.GetCell('C2').Value=15;const bytes=exportXlsx(book,{pivots:'flatten'}),loaded=(await importXlsx(bytes)).workbook;assert.equal(loaded.Worksheets.Get('Pivot').GetCell('B2').Value,15);assert.equal(sheet.GetCell('B2').Value,10);assert.equal(pivot.IsStale,true);});
test('source deletion can be rebound without restoring a deleted target',()=>{const {book,pivot,source,sheet}=sample();book.Worksheets.Remove(sheet);const newTarget=book.Worksheets.Add('NewPivot');pivot.Update({source:source.UsedRange,destination:newTarget.GetRange('A1')});assert.equal(pivot.InvalidReason,null);assert.equal(pivot.OutputRange.GetCell(1,1).Value,30);});
