import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {collectTrackedSource} from '../scripts/source-archive.mjs';
const SHA='a'.repeat(40);
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'gridweb-source-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']});git('init','-q');return{root,git,write:async(name,text)=>{await fs.mkdir(path.dirname(path.join(root,name)),{recursive:true});await fs.writeFile(path.join(root,name),text);git('add','--',name);}};}
test('source archives include tracked regular and executable files, never untracked secrets',async t=>{const f=await fixture(t);await f.write('src/main.js','export const n=1;');await f.write('run.sh','#!/bin/sh\ntrue\n');f.git('update-index','--chmod=+x','run.sh');await fs.writeFile(path.join(f.root,'credentials.txt'),'private');const source=await collectTrackedSource(f.root);assert.deepEqual(Object.keys(source).sort(),['GridWeb/run.sh','GridWeb/src/main.js']);assert.equal(source['GridWeb/src/main.js'].toString(),'export const n=1;');});
test('source archives record an uninitialized gitlink without trying to read a directory as a file',async t=>{const f=await fixture(t);await f.write('.gitmodules','[submodule "runtime"]\n path = runtime\n url = ../runtime.git\n');f.git('update-index','--add','--cacheinfo',`160000,${SHA},runtime`);const source=await collectTrackedSource(f.root),manifest=JSON.parse(source['GridWeb/SOURCE-GITLINKS.json']);assert.deepEqual(manifest.submodules,[{path:'runtime',commit:SHA}]);assert.equal(manifest.contentsIncluded,false);assert.equal(source['GridWeb/runtime'],undefined);});
test('source archives never sweep initialized submodule contents or private runtime files',async t=>{const f=await fixture(t);await f.write('README.md','root');f.git('update-index','--add','--cacheinfo',`160000,${SHA},runtime`);await fs.mkdir(path.join(f.root,'runtime'));await fs.writeFile(path.join(f.root,'runtime/private.json'),'secret');const source=await collectTrackedSource(f.root);assert.equal(Object.keys(source).some(k=>k.startsWith('GridWeb/runtime/')),false);});
test('source archives reject non-regular tracked modes',async t=>{const f=await fixture(t);await f.write('target','text');const blob=f.git('hash-object','target').trim();f.git('update-index','--add','--cacheinfo',`120000,${blob},symlink`);await assert.rejects(()=>collectTrackedSource(f.root),/regular source files/);});
test('source archives reject symlink filesystem entries and parents',async t=>{const f=await fixture(t);await f.write('src/file.txt','safe');await fs.rename(path.join(f.root,'src'),path.join(f.root,'elsewhere'));await fs.symlink(path.join(f.root,'elsewhere'),path.join(f.root,'src'),'junction');await assert.rejects(()=>collectTrackedSource(f.root),/Unsafe source filesystem entry/);});
test('source archives require a nonempty tracked index',async t=>{const f=await fixture(t);await assert.rejects(()=>collectTrackedSource(f.root),/tracked files/);});
test('source archives refuse a tracked reserved gitlink manifest',async t=>{const f=await fixture(t);await f.write('SOURCE-GITLINKS.json','{}');f.git('update-index','--add','--cacheinfo',`160000,${SHA},runtime`);await assert.rejects(()=>collectTrackedSource(f.root),/Reserved source manifest/);});
