<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows10.0.19041.0</TargetFramework><UseWinUI>true</UseWinUI><WindowsPackageType>None</WindowsPackageType><WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained><EnableMsixTooling>false</EnableMsixTooling><Platforms>x64</Platforms><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="../GridWeb.WinUI/GridWeb.WinUI.csproj"/></ItemGroup></Project>
