import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..');
const exists=async p=>!!await fs.stat(p).catch(()=>null);
const walk=async dir=>{const out=[];if(!await exists(dir))return out;for(const item of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,item.name);if(item.isDirectory())out.push(...await walk(p));else out.push(p);}return out;};
await fs.rm(path.join(root,'dist'),{recursive:true,force:true});await fs.rm(path.join(root,'site'),{recursive:true,force:true});await fs.mkdir(path.join(root,'dist'),{recursive:true});await fs.mkdir(path.join(root,'site'),{recursive:true});
for(const name of ['src','demo','docs','examples','types'])if(await exists(path.join(root,name))){await fs.cp(path.join(root,name),path.join(root,'dist',name),{recursive:true});await fs.cp(path.join(root,name),path.join(root,'site',name),{recursive:true});}
if(await exists(path.join(root,'integrations/vendor')))for(const dest of ['site','dist'])await fs.cp(path.join(root,'integrations/vendor'),path.join(root,dest,'integrations/vendor'),{recursive:true});
await fs.writeFile(path.join(root,'site','.nojekyll'),'');
await fs.writeFile(path.join(root,'site','index.html'),'<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=./demo/"><title>GridWeb Workbook Studio</title></head><body><a href="./demo/">Open GridWeb Workbook Studio</a></body></html>');
const sources={};for(const file of [...await walk(path.join(root,'src')),...await walk(path.join(root,'demo')),...await walk(path.join(root,'integrations/vendor'))])if(file.endsWith('.js')){const name=path.relative(root,file).split(path.sep).join('/');let code=await fs.readFile(file,'utf8');code=code.replace(/((?:from\s*|import\s*(?:\(\s*)?)['"])(\.\.?\/[^'"]+)(['"])/g,(_all,pre,ref,post)=>pre+'gridweb/'+path.posix.normalize(path.posix.join(path.posix.dirname(name),ref))+post);sources['gridweb/'+name]=code;}
let html=await fs.readFile(path.join(root,'demo/index.html'),'utf8');const css=await fs.readFile(path.join(root,'demo/style.css'),'utf8');html=html.replace('<link rel="stylesheet" href="./style.css">','<style>'+css+'</style>');
const boot=`<script>\nconst gridWebSources=${JSON.stringify(sources).replace(/</g,'\\u003c')};\nconst gridWebImports={};\nfor(const[name,source]of Object.entries(gridWebSources))gridWebImports[name]=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));\nconst gridWebImportMap=document.createElement('script');gridWebImportMap.type='importmap';gridWebImportMap.textContent=JSON.stringify({imports:gridWebImports});document.head.append(gridWebImportMap);\n</script><script type="module">import 'gridweb/demo/app.js';</script>`;
html=html.replace('<script type="module" src="./app.js"></script>',()=>boot);await fs.writeFile(path.join(root,'dist/GridWeb-standalone.html'),html);await fs.copyFile(path.join(root,'dist/GridWeb-standalone.html'),path.join(root,'site/GridWeb-standalone.html'));
const hostHTML='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GridWeb host</title><style>html,body{margin:0;height:100%;overflow:hidden}grid-web{height:100%;display:block}</style></head><body><grid-web></grid-web>'+boot.replace("import 'gridweb/demo/app.js'","import 'gridweb/src/host-page.js'")+'</body></html>';for(const dest of ['dist','site'])await fs.writeFile(path.join(root,dest,'GridWeb-host.html'),hostHTML);
const manifest={version:JSON.parse(await fs.readFile(path.join(root,'package.json'))).version,files:{}};for(const file of await walk(path.join(root,'src'))){const bytes=await fs.readFile(file);manifest.files[path.relative(root,file)]={size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};}await fs.writeFile(path.join(root,'dist/manifest.json'),JSON.stringify(manifest,null,2));console.log('Built modular browser distribution, Pages site and self-contained studio ('+Buffer.byteLength(html).toLocaleString()+' bytes).');
