import {Workbook, GridViewModel, PivotTable, analyzeRange, goalSeek, importDelimited, toDelimited, cellAddress, rangeAddress} from '../src/core.js';
import '../src/controls.js';
import {exportXlsx, importXlsx} from '../src/io.js';
import {escapeHTML} from '../src/layout.js';
import {createShowcase, createLargeShowcase} from './fixtures.js';
import {companionBundle} from './build-info.js';
const $=id=>document.getElementById(id),grid=$('grid');let workbook,viewModel,subscription,panel='cell',saveTimer,toastTimer,currentTab='Home',selectedChart=null,companion=null;
const iconPaths={paste:'M8 5H5v16h14V5h-3 M8 3h8v4H8z M8 12h8 M8 16h6',undo:'M9 5L4 10l5 5 M4 10h9a6 6 0 0 1 6 6',redo:'M15 5l5 5-5 5 M20 10h-9a6 6 0 0 0-6 6',grid:'M3 4h18v16H3z M3 9h18 M3 14h18 M9 4v16 M15 4v16',chart:'M4 3v18h17 M8 17v-6 M13 17V6 M18 17V9',formula:'M16 4c-4-2-7 0-7 4l-2 12 M5 10h10 M13 14l6 6 M19 14l-6 6',sort:'M4 5h10 M4 10h7 M4 15h4 M18 4v16 M14 16l4 4 4-4',filter:'M3 4h18l-7 8v7l-4 2V12z',comment:'M4 4h16v13H9l-5 4z M8 8h8 M8 12h6',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7-10-7-10-7z M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6',save:'M4 3h13l4 4v14H3V3z M7 3v6h9V3 M7 21v-8h10v8',open:'M3 6h7l2 3h9l-3 11H3z M3 6V4h7l2 2h8v3',print:'M7 9V3h10v6 M7 17H3V9h18v8h-4 M7 14h10v7H7z',plus:'M12 4v16 M4 12h16',protect:'M5 10h14v11H5z M8 10V6a4 4 0 0 1 8 0v4 M12 14v3',check:'M3 12l6 6L21 6',find:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6',row:'M3 4h18v16H3z M3 9h18 M3 14h18',align:'M4 5h16 M4 10h10 M4 15h16 M4 20h10',merge:'M3 5h6v14H3 M15 5h6v14h-6 M6 12h12 M9 9l-3 3 3 3 M15 9l3 3-3 3',clear:'M5 16l8-12 8 5-8 12H9z M5 16l8 5 M16 21h6',theme:'M12 3a9 9 0 1 0 9 9 7 7 0 0 1-9-9z'};
function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${iconPaths[name]??iconPaths.grid}"/></svg>`;}
function button(id,label,glyph,small=false){const b=document.createElement('button');b.className='ribbon-button'+(small?' small':'');b.dataset.command=id;b.title=label;b.innerHTML=icon(glyph)+`<span>${escapeHTML(label)}</span>`;return b;}
function group(label,items,wrap=false){const div=document.createElement('section');div.className='ribbon-group';div.dataset.group=label;div.innerHTML=`<div class="group-items${wrap?' wrap':''}"></div><div class="group-label">${escapeHTML(label)}</div>`;for(const item of items)div.firstChild.append(Array.isArray(item)?button(...item):item);return div;}
function select(options,value,handler,cls=''){const e=document.createElement('select');e.className=cls;for(const [v,t]of options){const o=document.createElement('option');o.value=v;o.textContent=t;e.append(o);}e.value=value;e.addEventListener('change',()=>attempt(()=>handler(e.value)));return e;}
function renderRibbon(){const r=$('ribbon');r.replaceChildren();document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===currentTab)));const add=(...args)=>r.append(group(...args));
 if(currentTab==='Home'){
  add('Clipboard',[['paste','Paste','paste'],['copy','Copy','grid',true],['undo','Undo','undo',true],['redo','Redo','redo',true]]);
  const fonts=document.createElement('div');fonts.className='format-row';fonts.append(select(['Aptos','Segoe UI','Arial','Georgia','Consolas'].map(x=>[x,x]),'Aptos',v=>grid.SelectionRange.SetStyle({font:{name:v}}),'font-select'),select([9,10,11,12,14,16,18,24,32].map(x=>[x,x]),11,v=>grid.SelectionRange.SetStyle({font:{size:+v}}),'size-select'));
  const tools=document.createElement('div');tools.className='format-row';for(const [cmd,label,style]of [['bold','B','font-weight:750'],['italic','I','font-style:italic'],['underline','U','text-decoration:underline']]){const b=button(cmd,label,null,true);b.innerHTML=label;b.style.cssText=style;tools.append(b);}for(const[k,title,value]of[['fill','Cell fill','#e1efe6'],['color','Font color','#107c41']]){const i=document.createElement('input');i.type='color';i.value=value;i.title=i.ariaLabel=title;i.addEventListener('input',()=>attempt(()=>grid.SelectionRange.SetStyle(k==='fill'?{fill:i.value}:{font:{color:i.value}})));tools.append(i);}tools.append(button('border','Borders','grid',true));add('Font',[fonts,tools],true);
  add('Alignment',[['alignLeft','Align left','align',true],['alignCenter','Center','align',true],['wrap','Wrap text','row',true],['merge','Merge cells','merge',true]],true);
  add('Number',[select([['General','General'],['$#,##0.00','Currency'],['0.0%','Percentage'],['#,##0.00','Number'],['yyyy-mm-dd','Short date'],['0.00E+00','Scientific']],'General',v=>grid.SelectionRange.Format.NumberFormat=v,'number-select'),['percent','%','formula',true]],true);
  add('Styles',[['conditional','Conditional\nformatting','chart'],['table','Format as\ntable','grid']]);add('Cells',[['insertRow','Insert row','plus',true],['deleteRow','Delete row','clear',true],['autofit','AutoFit','row',true]],true);add('Editing',[['autosum','AutoSum','formula'],['sort','Sort & filter','sort'],['find','Find & replace','find']]);
 }else if(currentTab==='Insert'){add('Tables',[['table','Table','grid'],['pivot','Pivot table','grid']]);add('Charts',[['chartColumn','Column','chart'],['chartLine','Line','chart'],['chartBar','Bar','chart'],['chartPie','Pie','chart'],['chartScatter','Scatter','chart'],['chartArea','Area','chart']]);add('Annotations',[['comment','Cell note','comment'],['names','Named range','formula']]);add('Structure',[['addSheet','Worksheet','plus'],['insertRow','Insert row','row'],['insertColumn','Insert column','grid']]);
 }else if(currentTab==='Page Layout'){add('Page setup',[['pageSetup','Page setup','print'],['printArea','Set print area','grid'],['clearPrintArea','Clear print area','clear'],['preview','Print preview','eye'],['print','Print','print']]);add('Layout',[['freeze','Freeze panes','grid'],['unfreeze','Unfreeze','row'],['gridlines','Gridlines','grid']]);
 }else if(currentTab==='Formulas'){add('Function library',[['functions','Insert function','formula'],['autosum','AutoSum','formula'],['formulaLab','Formula lab','grid']]);add('Defined names',[['names','Define name','formula'],['nameManager','Name manager','grid']]);add('Formula auditing',[['trace','Trace precedents','eye'],['recalculate','Calculate now','formula'],['calcMode','Calculation mode','row']]);
 }else if(currentTab==='Data'){add('Import / export',[['open','Open workbook','open'],['xlsx','Export XLSX','save'],['csv','Export CSV','save']]);add('Sort & filter',[['sort','Sort','sort'],['filter','Filter','filter'],['clearFilter','Clear filter','clear']]);add('Data tools',[['validation','Data validation','check'],['dedup','Remove duplicates','row'],['pivot','Pivot table','grid'],['goalSeek','Goal seek','formula']]);
 }else if(currentTab==='Review'){add('Comments',[['comment','Edit note','comment'],['removeComment','Delete note','clear']]);add('Protection',[['protect','Protect / unprotect','protect'],['readOnly','Read-only view','eye']]);add('Quality',[['errors','Find errors','find'],['help','API & boundaries','eye']]);
 }else if(currentTab==='View'){add('Workbook views',[['normal','Normal','grid'],['preview','Page layout','print'],['pageBreak','Page breaks','row']]);add('Show',[['gridlines','Gridlines','grid'],['inspector','Inspector','eye'],['theme','Light / dark','theme']]);add('Window',[['freeze','Freeze panes','grid'],['unfreeze','Unfreeze','row'],['zoom100','100%','find']]);add('Developer tools',[['large','Large workbook','grid'],['ecosystem','Companion libraries','grid'],['reset','Reset sample','undo']]);}
}
function toast(message){$('toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',4200);}
async function attempt(action){try{return await action();}catch(e){toast(e.message??String(e));console.error('GridWeb command:',e);}}
function setBook(book){subscription?.Dispose();viewModel?.Dispose();companion?.Dispose?.();companion=null;workbook=book;viewModel=new GridViewModel(book);grid.DataContext=viewModel;$('book-title').value=book.Name;subscription=book.Changed.Subscribe(()=>{renderSheets();renderPanel();updateSelection();$('saved').textContent='Unsaved changes';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('gridweb.workbook.v1',JSON.stringify(book.ToJSON()));$('saved').textContent='Saved locally';}catch{$('saved').textContent='Not saved — export your workbook';}},350);});renderSheets();renderPanel();updateSelection();window.gridweb={workbook,grid,viewModel,commands,createShowcase,createLargeShowcase};}
function renderSheets(){const tabs=$('sheet-tabs');tabs.replaceChildren();for(const s of workbook.Worksheets){const b=document.createElement('button');b.textContent=s.Name;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(s===grid.Sheet));b.addEventListener('click',()=>{grid.Sheet=s;renderSheets();renderPanel();});b.addEventListener('dblclick',()=>showDialog('Rename worksheet',[{name:'name',label:'Worksheet name',value:s.Name}],v=>{s.Name=v.name;renderSheets();}));tabs.append(b);}}
function updateSelection(){if(!workbook)return;$('address').value=grid.Selection;if(document.activeElement!==$('formula'))$('formula').value=grid.ActiveCell.Input??'';try{const stats=analyzeRange(grid.SelectionRange);$('stats').textContent=`Average: ${stats.average.toLocaleString(undefined,{maximumFractionDigits:2})}    Count: ${stats.count}    Sum: ${stats.sum.toLocaleString(undefined,{maximumFractionDigits:2})}`;}catch{$('stats').textContent='Selection exceeds analysis limit';}renderPanel();}
function kv(name,value){return `<div class="kv"><span>${escapeHTML(name)}</span><b>${escapeHTML(value)}</b></div>`;}
function renderPanel(){if(!workbook)return;document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('selected',b.dataset.panel===panel));const holder=$('panel-content'),cell=grid.ActiveCell;let html='';
 if(panel==='cell'){html=`<p class="eyebrow">${escapeHTML(grid.Sheet.Name)}</p><div class="cell-heading">${escapeHTML(grid.Selection)}</div><p class="hint">${cell.Formula?'Formula cell':'Workbook selection'}</p><div class="section"><p class="eyebrow">Value & formatting</p>${kv('Displayed value',cell.Text.length>55?cell.Text.slice(0,55)+'…':cell.Text)}${kv('Data type',cell.Formula?'Formula':cell.Value===null?'Empty':typeof cell.Value)}${kv('Number format',cell.Style.numberFormat??'General')}</div>`;if(cell.Formula)html+=`<div class="code-box">${escapeHTML(cell.Formula)}</div>`;html+=`<button class="panel-button" data-command="comment">${cell.Comment?'Edit cell note':'＋ Add cell note'}</button>`;if(cell.Comment)html+=`<p class="hint">${escapeHTML(cell.Comment)}</p>`;html+=`<div class="section"><p class="eyebrow">Workbook</p>${kv('Worksheets',workbook.Worksheets.Count)}${kv('Stored cells',workbook._sheets.reduce((n,s)=>n+s.CellCount,0).toLocaleString())}${kv('Built-in functions',workbook.Calculation.FunctionNames.length)}<span class="pill">Same model · every view</span></div><div class="section"><p class="eyebrow">Try it</p><p class="hint">Double-click a cell to edit. Drag the selection’s fill handle to extend a series. Resize columns at their header edge. All changes are undoable.</p><button class="panel-button" data-command="trace">Trace formula dependencies →</button></div>`;
 }else if(panel==='analysis'){let stats;try{stats=analyzeRange(grid.SelectionRange);}catch{}html=`<p class="eyebrow">Selection analysis</p><div class="cell-heading">${escapeHTML(grid.Selection)}</div>${stats?Object.entries(stats).map(([k,v])=>kv(k,v.toLocaleString(undefined,{maximumFractionDigits:3}))).join(''):'<p class="hint">Select a smaller range for aggregate analysis.</p>'}<div class="section"><p class="eyebrow">Rendering diagnostics</p>${kv('Visible cells',grid.Metrics.visibleCells)}${kv('Last canvas pass',grid.Metrics.renderMs.toFixed(2)+' ms')}${kv('Formula evaluations',workbook.Calculation.EvaluationCount)}<p class="hint">Measured locally. Frame time is not a cross-device performance guarantee.</p></div><button class="panel-button" data-command="pivot">Create a pivot summary →</button><button class="panel-button" data-command="goalSeek">Run goal seek →</button>`;
 }else{const entries=[['RibbonWeb','Reusable command ribbon'],['Dockyard','Dockable document and tool panes'],['TreeDataGridWeb','Observable cell inspector'],['DynamicDataWeb','Live cell-change cache'],['ReactiveWeb','Commands and observable view model'],['RBushWeb','Chart rectangle spatial index'],['QuikGraphWeb','Formula dependency graph']];html=`<p class="eyebrow">Companion integrations</p><span class="pill">${companion?'Connected':companionBundle?'Bundle ready':'Buildable source adapters'}</span><p class="hint">${companion?'The companion controls are operating on this workbook.':'The default studio needs no dependencies. Companion packages require a separate local build; they are not silently loaded from a CDN.'}</p>${entries.map(([a,b])=>`<div class="library"><b>${a}</b><span>${b}</span></div>`).join('')}<button class="panel-button" data-command="loadIntegrations">${companionBundle?'Activate companion workspace':'Integration build instructions'} →</button>`;}
 holder.innerHTML=html;
}
function showDialog(title,fields,apply,{submit='Apply',description=''}={}){const d=$('dialog');$('dialog-title').textContent=title;$('dialog-fields').replaceChildren();$('dialog-error').textContent='';$('submit-dialog').textContent=submit;if(description){const p=document.createElement('p');p.className='hint';p.textContent=description;$('dialog-fields').append(p);}for(const f of fields){const label=document.createElement('label'),span=document.createElement('span');span.textContent=f.label;label.append(span);let input;if(f.options){input=document.createElement('select');for(const option of f.options){const[v,t]=Array.isArray(option)?option:[option,option],o=document.createElement('option');o.value=v;o.textContent=t;input.append(o);}}else{input=document.createElement(f.type==='textarea'?'textarea':'input');if(f.type!=='textarea')input.type=f.type??'text';}input.name=f.name;input.value=f.value??'';if(f.placeholder)input.placeholder=f.placeholder;label.append(input);$('dialog-fields').append(label);}$('dialog-form').onsubmit=async e=>{e.preventDefault();try{const values=Object.fromEntries(new FormData(e.currentTarget));await apply(values);d.close();updateSelection();}catch(error){$('dialog-error').textContent=error.message;}};d.showModal();}
function download(name,data,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Exported '+name);}
function formatFont(key){grid.SelectionRange.SetStyle({font:{[key]:!grid.ActiveCell.Style.font?.[key]}});}
function chart(type){showDialog('Insert '+type+' chart',[{name:'range',label:'Source range (headers in first row, categories in first column)',value:grid.SelectionRange.RowCount>1?grid.Selection:'A5:C17'},{name:'title',label:'Chart title',value:'Workbook chart'}],v=>{const chart=grid.Sheet.AddChart(v.range,{type,title:v.title,row:grid.SelectionRange.Bounds.r1+2,column:Math.min(16378,grid.SelectionRange.Bounds.c2+2)});selectedChart=chart;toast('Chart added. Drag it to move; drag the lower-right corner to resize.');});}
const commands={
 undo:()=>workbook.Undo(),redo:()=>workbook.Redo(),copy:()=>grid.CopySelection(),paste:()=>grid.Paste(),bold:()=>formatFont('bold'),italic:()=>formatFont('italic'),underline:()=>formatFont('underline'),border:()=>grid.SelectionRange.SetStyle({border:!grid.ActiveCell.Style.border}),alignLeft:()=>grid.SelectionRange.SetStyle({horizontalAlignment:'left'}),alignCenter:()=>grid.SelectionRange.SetStyle({horizontalAlignment:'center'}),wrap:()=>grid.SelectionRange.SetStyle({wrapText:!grid.ActiveCell.Style.wrapText}),merge:()=>grid.SelectionRange.Merge(),percent:()=>grid.SelectionRange.Format.NumberFormat='0.0%',autofit:()=>grid.SelectionRange.Format.AutoFitColumns(),
 insertRow:()=>grid.Sheet.InsertRows(grid.SelectionRange.Bounds.r1),deleteRow:()=>grid.Sheet.DeleteRows(grid.SelectionRange.Bounds.r1),insertColumn:()=>grid.Sheet.InsertColumns(grid.SelectionRange.Bounds.c1),deleteColumn:()=>grid.Sheet.DeleteColumns(grid.SelectionRange.Bounds.c1),
 autosum:()=>{const r=grid.SelectionRange;if(r.RowCount>1){const dest=r.Offset(r.RowCount,0).Resize(1,r.ColumnCount);workbook.Transaction('AutoSum',()=>{for(let c=0;c<r.ColumnCount;c++)dest.GetCell(0,c).Formula='SUM('+r.Offset(0,c).Resize(r.RowCount,1).Address+')';});grid.Select(dest.Address);}else{const b=r.Bounds;if(b.r1===0)throw new Error('Select data or a cell below numeric values.');grid.ActiveCell.Formula=`SUM(${cellAddress(0,b.c1)}:${cellAddress(b.r1-1,b.c1)})`;}},
 addSheet:()=>showDialog('Add worksheet',[{name:'name',label:'Worksheet name',value:'Sheet'+(workbook.Worksheets.Count+1)}],v=>{grid.Sheet=workbook.Worksheets.Add(v.name);renderSheets();}),
 table:()=>showDialog('Format as table',[{name:'range',label:'Range',value:grid.SelectionRange.RowCount>1?grid.Selection:grid.Sheet.UsedRange.Address},{name:'name',label:'Table name',value:'Table'+(workbook._sheets.reduce((n,s)=>n+s.Tables.length,0)+1)}],v=>grid.Sheet.AddTable(v.range,v.name)),
 sort:()=>showDialog('Sort worksheet range',[{name:'range',label:'Range (first row is the header)',value:grid.SelectionRange.RowCount>1?grid.Selection:grid.Sheet.UsedRange.Address},{name:'column',label:'Sort column within range (1-based)',type:'number',value:1},{name:'order',label:'Order',options:['Ascending','Descending']}],v=>grid.Sheet.GetRange(v.range).Sort([{column:+v.column-1,ascending:v.order!=='Descending'}])),
 filter:()=>showDialog('Filter data',[{name:'range',label:'Data range including headers',value:grid.Sheet.Tables[0]?rangeAddress(grid.Sheet.Tables[0].range):grid.Sheet.UsedRange.Address},{name:'column',label:'Filter column within range (1-based)',type:'number',value:1},{name:'value',label:'Criterion (examples: >=100, On track, *west*)',value:'*'}],v=>grid.Sheet.SetFilter(v.range,[{column:+v.column-1,value:v.value}])),clearFilter:()=>grid.Sheet.ClearFilter(),
 conditional:()=>showDialog('Conditional formatting',[{name:'range',label:'Range',value:grid.Selection},{name:'type',label:'Rule',options:[['dataBar','Data bars'],['colorScale','Color scale'],['cellValue','Less than a value'],['duplicate','Duplicate values']]},{name:'value',label:'Comparison value',value:0}],v=>grid.Sheet.AddConditionalFormat(v.range,{type:v.type,operator:'lessThan',value:+v.value,color:'#72bf91',style:{fill:'#fff0df',font:{color:'#ad591f'}}})),
 validation:()=>showDialog('Data validation',[{name:'range',label:'Range',value:grid.Selection},{name:'type',label:'Rule',options:[['list','List'],['number','Decimal range'],['whole','Whole-number range']]},{name:'values',label:'List values, separated by commas',value:'Ready,In progress,Review'},{name:'min',label:'Minimum',value:0},{name:'max',label:'Maximum',value:1000000}],v=>grid.Sheet.AddValidation(v.range,{type:v.type,values:v.values.split(',').map(s=>s.trim()),min:+v.min,max:+v.max})),
 dedup:()=>{const r=grid.SelectionRange.RowCount>1?grid.SelectionRange:grid.Sheet.UsedRange;toast(r.RemoveDuplicates()+' duplicate rows removed.');},
 pivot:()=>showDialog('Pivot table',[{name:'sheet',label:'Source worksheet',value:workbook.Worksheets.Get('Transactions')?'Transactions':grid.Sheet.Name,options:[...workbook.Worksheets].map(s=>s.Name)},{name:'range',label:'Source range (blank = used range)',value:''},{name:'rows',label:'Row field (header text or 1-based index)',value:'1'},{name:'columns',label:'Column field (optional)',value:''},{name:'value',label:'Value field',value:'4'},{name:'aggregate',label:'Aggregate',options:['sum','average','count','min','max','distinct']}],v=>{const source=workbook.Worksheets.Get(v.sheet),field=s=>/^\d+$/.test(s)?+s-1:s,pivot=new PivotTable(v.range?source.GetRange(v.range):source.UsedRange,{rows:[field(v.rows)],columns:v.columns?[field(v.columns)]:[],values:[{column:field(v.value),aggregate:v.aggregate,name:v.aggregate}]});let name='Pivot '+(workbook.Worksheets.Count+1);const sheet=workbook.Worksheets.Add(name);pivot.WriteTo(sheet.GetRange('A1'));sheet.GetRangeByIndexes(0,0,1,pivot.Result[0].length).SetStyle({fill:'#107c41',font:{bold:true,color:'#fff'}});sheet.UsedRange.Format.ColumnWidth=145;grid.Sheet=sheet;renderSheets();}),
 goalSeek:()=>showDialog('Goal seek',[{name:'formula',label:'Formula cell',value:grid.ActiveCell.Address},{name:'input',label:'Changing input cell',value:'B6'},{name:'target',label:'Target value',value:'100000'}],v=>{const result=goalSeek(grid.Sheet.GetCell(v.formula),grid.Sheet.GetCell(v.input),+v.target);toast('Solved: '+result.value.toPrecision(9)+' in '+result.iterations+' iterations');}),
 names:()=>showDialog('Define name',[{name:'name',label:'Name',value:'MyRange'},{name:'formula',label:'Refers to (range, formula or LAMBDA)',value:'='+grid.SelectionRange.FullAddress}],v=>workbook.DefineName(v.name,v.formula)),
 nameManager:()=>showDialog('Defined names',[{name:'name',label:'Name',value:[...workbook.Names][0]?.[0]??'',options:[...workbook.Names].map(([n])=>n)},{name:'action',label:'Action',options:['Navigate','Delete']}],v=>{if(v.action==='Delete')workbook.RemoveName(v.name);else{const f=workbook.Names.Get(v.name);grid.Select(String(f).replace(/^=/,''));renderSheets();}},{description:[...workbook.Names].map(([n,v])=>n+' = '+v).join('  •  ')}),
 trace:()=>{const edges=workbook.Calculation.GetDependencyEdges(),id=grid.Sheet.Id+':'+grid.ActiveCell.Address;showDialog('Formula dependencies',[{name:'details',label:'Direct dependency edges (source → dependent)',type:'textarea',value:JSON.stringify(edges.filter(e=>JSON.stringify(e).includes(id)),null,2)}],()=>{},{submit:'Close',description:'Cell edges are listed here. Large range dependencies are tracked separately by the engine.'});},
 functions:()=>{showDialog('Insert function',[{name:'search',label:'Search the function library',value:''}],()=>{},{submit:'Close',description:'Choose a function to start editing the active cell. Arguments are entered using comma separators.'});const list=document.createElement('div');list.className='function-list';$('dialog-fields').append(list);const render=q=>{list.replaceChildren();for(const name of workbook.Calculation.FunctionNames.filter(n=>n.includes(q.toUpperCase()))){const b=document.createElement('button');b.type='button';b.textContent=name;b.addEventListener('click',()=>{$('dialog').close();grid.BeginEdit('='+name+'(');});list.append(b);}};render('');$('dialog-fields').querySelector('input').addEventListener('input',e=>render(e.target.value));},
 formulaLab:()=>{const s=workbook.Worksheets.Get('Formula lab');if(!s)throw new Error('Open the showcase workbook to use the Formula lab.');grid.Sheet=s;renderSheets();},recalculate:()=>{workbook.Calculate(true);toast('Workbook recalculated');},calcMode:()=>{workbook.CalculationMode=workbook.CalculationMode==='Automatic'?'Manual':'Automatic';if(workbook.CalculationMode==='Automatic')workbook.Calculate();toast('Calculation: '+workbook.CalculationMode);},
 comment:()=>showDialog('Cell note · '+grid.ActiveCell.Address,[{name:'note',label:'Note',type:'textarea',value:grid.ActiveCell.Comment}],v=>grid.ActiveCell.Comment=v.note),removeComment:()=>grid.ActiveCell.Comment='',protect:()=>{grid.Sheet.IsProtected?grid.Sheet.Unprotect():grid.Sheet.Protect();toast(grid.Sheet.IsProtected?'Worksheet protected (editing guard, not encryption)':'Worksheet unprotected');},readOnly:()=>{grid.ReadOnly=!grid.ReadOnly;toast(grid.ReadOnly?'Read-only presentation':'Editing enabled');},
 errors:()=>{const results=[];for(const s of workbook.Worksheets)for(const[n]of s._cells){const c=s.GetCell(Math.floor(n/16384),n%16384);if(c.Value?.code)results.push(s.Name+'!'+c.Address+'  '+c.Value.code);}showDialog('Workbook formula errors',[{name:'errors',label:results.length+' errors',type:'textarea',value:results.join('\n')||'No calculated errors found.'}],()=>{},{submit:'Close'});},
 find:()=>showDialog('Find & replace',[{name:'query',label:'Find',value:''},{name:'replacement',label:'Replace with',value:''},{name:'action',label:'Action',options:['Find next','Replace all']}],v=>{if(v.action==='Replace all')toast(workbook.Replace(v.query,v.replacement)+' cells replaced');else{const hits=workbook.Find(v.query);if(!hits.length)throw new Error('No matching cells.');const current=hits.findIndex(h=>h.sheet===grid.Sheet&&h.address===grid.ActiveCell.Address),hit=hits[(current+1)%hits.length];grid.Sheet=hit.sheet;grid.Select(hit.address);renderSheets();toast(hits.length+' matching cells');}}),
 freeze:()=>showDialog('Freeze panes',[{name:'rows',label:'Leading rows (0–100)',type:'number',value:Math.min(100,grid.SelectionRange.Bounds.r1)||1},{name:'columns',label:'Leading columns (0–100)',type:'number',value:Math.min(100,grid.SelectionRange.Bounds.c1)}],v=>grid.Sheet.FreezePanes(+v.rows,+v.columns)),unfreeze:()=>grid.Sheet.FreezePanes(0,0),
 printArea:()=>grid.Sheet._setMeta('print',{...grid.Sheet._meta.print,area:grid.SelectionRange.Bounds}),clearPrintArea:()=>grid.Sheet._setMeta('print',{...grid.Sheet._meta.print,area:null}),
 pageSetup:()=>showDialog('Page setup',[{name:'paper',label:'Paper',options:['A4','Letter'],value:grid.Sheet._meta.print.paper},{name:'orientation',label:'Orientation',options:['portrait','landscape'],value:grid.Sheet._meta.print.orientation},{name:'scale',label:'Scale (%)',type:'number',value:(grid.Sheet._meta.print.scale??1)*100},{name:'repeatRows',label:'Repeat leading rows',type:'number',value:grid.Sheet._meta.print.repeatRows??0}],v=>grid.Sheet._setMeta('print',{...grid.Sheet._meta.print,paper:v.paper,orientation:v.orientation,scale:+v.scale/100,repeatRows:+v.repeatRows})),
 normal:()=>setView('normal'),preview:()=>setView('pageLayout'),pageBreak:()=>setView('pageBreak'),print:()=>grid.Print(),gridlines:()=>grid.ShowGridLines=!grid.ShowGridLines,zoom100:()=>setZoom(100),inspector:()=>{$('inspector').hidden=!$('inspector').hidden;grid.Refresh();},theme:()=>{const dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);grid.Theme=dark?'dark':'light';try{localStorage.setItem('gridweb.theme',grid.Theme);}catch{}},
 open:()=>$('open-file').click(),save:()=>download(workbook.Name+'.gridweb.json',JSON.stringify(workbook.ToJSON(),null,2),'application/json'),xlsx:()=>download(workbook.Name+'.xlsx',exportXlsx(workbook,{onWarning:toast}),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'),csv:()=>download(grid.Sheet.Name+'.csv',toDelimited(grid.SelectionRange.RowCount>1?grid.SelectionRange:grid.Sheet.UsedRange),'text/csv;charset=utf-8'),
 file:()=>showDialog('Workbook files',[{name:'action',label:'Action',options:[['save','Save GridWeb JSON'],['xlsx','Export Excel workbook (.xlsx)'],['csv','Export worksheet CSV'],['open','Open JSON / CSV / TSV / XLSX'],['new','New blank workbook']]}],v=>v.action==='new'?setBook(new Workbook()):commands[v.action](),{description:'Files are processed locally. No workbook is uploaded to a service.'}),
 reset:()=>showDialog('Reset showcase',[],()=>setBook(createShowcase()),{description:'This replaces the current in-browser workbook. Export your changes first.',submit:'Reset showcase'}),
 large:()=>showDialog('Virtualization laboratory',[{name:'rows',label:'Generated rows',options:[['1000','1,000'],['10000','10,000'],['20000','20,000'],['50000','50,000']],value:'20000'}],async v=>{await new Promise(requestAnimationFrame);const start=performance.now();setBook(createLargeShowcase(+v.rows));toast('Generated and calculated in '+(performance.now()-start).toFixed(0)+' ms. Go to XFD1048576 to inspect the final address.');},{description:'Replaces the workbook with sparse, editable data. Only visible cells are rendered.'}),
 ecosystem:()=>{panel='ecosystem';$('inspector').hidden=false;renderPanel();},
 loadIntegrations:async()=>{if(!companionBundle){showDialog('Build the companion workspace',[{name:'commands',label:'Run in the source directory',type:'textarea',value:'npm --prefix integrations install\nnpm run build:integrations\nnpm run build\nnpm run dev'}],()=>{},{submit:'Close',description:'All seven source adapters are included. Packages are not bundled in this offline build because registry access was unavailable during development.'});return;}const {attachCompanions}=await import('../integrations/vendor/index.js');companion=await attachCompanions({workbook,grid,commands,documentPane:$('document-pane'),inspector:$('inspector'),workspace:$('workspace'),ribbonHost:$('companion-ribbon')});$('ribbon').hidden=true;renderPanel();},
 help:()=>showDialog('GridWeb · API and compatibility',[{name:'usage',label:'Headless API',type:'textarea',value:"import { Workbook } from '@wieslawsoltes/gridweb';\nconst book = new Workbook();\nconst sheet = book.Worksheets.Get(0);\nsheet.GetRange('A1:B2').Values = [[1,2],[3,4]];\nsheet.GetCell('C1').Formula = 'SUM(A1:B2)';\nconsole.log(sheet.GetCell('C1').Value); // 10\ngrid.Workbook = book;"}],()=>{},{submit:'Close',description:'Independent preview implementation, not full Microsoft Excel or Office.js parity. VBA, Power Query/DAX, production coauthoring, lossless arbitrary XLSX and native Windows runtime qualification are not provided. Read README.md and docs/compatibility.md in the source package.'})
};
for(const type of ['Column','Line','Bar','Pie','Scatter','Area'])commands['chart'+type]=()=>chart(type.toLowerCase());
function setView(mode){grid.ViewMode=mode;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===mode));}
function setZoom(value){grid.Zoom=Math.max(.5,Math.min(2,+value/100));$('zoom').value=grid.Zoom*100;$('zoom-value').textContent=Math.round(grid.Zoom*100)+'%';}
document.addEventListener('click',e=>{const b=e.target.closest('[data-command]');if(b&&commands[b.dataset.command])attempt(commands[b.dataset.command]);const tab=e.target.closest('[data-tab]');if(tab){currentTab=tab.dataset.tab;renderRibbon();}const p=e.target.closest('[data-panel]');if(p){panel=p.dataset.panel;renderPanel();}const v=e.target.closest('[data-view]');if(v)setView(v.dataset.view);});
$('search-button').onclick=commands.find;$('cancel-dialog').onclick=$('close-dialog').onclick=()=>$('dialog').close();
$('address').addEventListener('keydown',e=>{if(e.key==='Enter')attempt(()=>{grid.Select(e.target.value);renderSheets();grid.Focus();});});
function commitFormula(){attempt(()=>{grid.ActiveCell.Input=$('formula').value;grid.Focus();updateSelection();});}
$('formula').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();commitFormula();}if(e.key==='Escape'){e.target.value=grid.ActiveCell.Input??'';grid.Focus();}});$('commit-formula').onclick=commitFormula;$('cancel-formula').onclick=()=>$('formula').value=grid.ActiveCell.Input??'';
$('book-title').addEventListener('change',e=>{workbook.Name=e.target.value.slice(0,160)||'Book1';toast('Workbook renamed');});
$('zoom').oninput=e=>setZoom(e.target.value);$('zoom-out').onclick=()=>setZoom(grid.Zoom*100-10);$('zoom-in').onclick=()=>setZoom(grid.Zoom*100+10);
function moveSheet(delta){const sheets=[...workbook.Worksheets],index=sheets.indexOf(grid.Sheet);grid.Sheet=sheets[(index+delta+sheets.length)%sheets.length];renderSheets();}
$('previous-sheet').onclick=()=>moveSheet(-1);$('next-sheet').onclick=()=>moveSheet(1);
grid.addEventListener('selection-change',updateSelection);grid.addEventListener('chart-select',e=>{selectedChart=e.detail.chart;toast(selectedChart.title+' · Drag to move, lower-right corner to resize, Delete to remove.');});grid.addEventListener('grid-render',()=>{$('status').textContent=(grid.ReadOnly?'Read only':'Ready')+' · '+grid.Metrics.visibleCells+' visible cells';});
$('open-file').addEventListener('change',e=>attempt(async()=>{const file=e.target.files[0];if(!file)return;if(file.size>32*1024*1024)throw new Error('File exceeds the 32 MiB import limit.');if(/\.xlsx$/i.test(file.name)){const result=await importXlsx(new Uint8Array(await file.arrayBuffer()));setBook(result.workbook);toast(result.warnings.length?result.warnings.length+' import warnings; review the console.':'Workbook opened');if(result.warnings.length)console.warn('XLSX import warnings:',result.warnings);}else{const text=await file.text();if(/\.json$/i.test(file.name))setBook(Workbook.FromJSON(text));else{const book=new Workbook({name:file.name});importDelimited(book.ActiveWorksheet,text,{delimiter:/\.tsv$/i.test(file.name)?'\t':','});book.ClearHistory();setBook(book);}}e.target.value='';}));
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();commands.save();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();if(!$('dialog').open)commands.find();}});
let initial;try{const saved=localStorage.getItem('gridweb.workbook.v1');initial=saved?Workbook.FromJSON(saved):createShowcase();const theme=localStorage.getItem('gridweb.theme');if(theme==='dark'){document.body.classList.add('dark');grid.Theme='dark';}}catch(e){console.warn('Stored workbook unavailable:',e.message);initial=createShowcase();}
setBook(initial);renderRibbon();grid.Select('C8');
