import { Workbook, GridViewModel } from './model.js';
import { EventSource } from './events.js';
import { cellAddress, parseCell, parseRange, rangeAddress, columnName, contains, shiftFormula, MAX_ROWS, MAX_COLUMNS, MAX_OPERATION_CELLS } from './address.js';
import { isError, truth, scalar } from './errors.js';
import { toDelimited, importDelimited } from './data.js';
import { AxisLayout, paginate, safeColor, printPagesHTML, printCSS, createPrintDocument } from './layout.js';
import { drawChart } from './charts.js';
import { criteriaPredicate } from './functions.js';
const Base = globalThis.HTMLElement ?? class {};
const styles=`:host{display:block;position:relative;min-width:0;min-height:120px;height:100%;contain:layout style;--grid-bg:#fff;--grid-fg:#24332a;--grid-line:#e2e7e3;--grid-head:#f6f8f6;--grid-head-active:#e1efe6;--grid-accent:#107c41;font:12px system-ui}:host([theme=dark]){--grid-bg:#19231d;--grid-fg:#e7eee9;--grid-line:#354138;--grid-head:#202d24;--grid-head-active:#284d36;--grid-accent:#52c187}.root{position:absolute;inset:0;overflow:hidden;background:var(--grid-bg);color:var(--grid-fg);outline:none}.root:focus-visible{outline:2px solid var(--grid-accent);outline-offset:-2px}.scroller{position:absolute;inset:0;overflow:scroll;scrollbar-width:thin;scrollbar-color:#b7c9bc var(--grid-head)}.spacer{pointer-events:none}.canvas{position:absolute;left:0;top:0;touch-action:none}.editor,.validation{position:absolute;box-sizing:border-box;z-index:5;border:2px solid var(--grid-accent);background:var(--grid-bg);color:var(--grid-fg);font:13px system-ui;padding:3px 5px;resize:none;outline:none;min-height:24px;box-shadow:0 3px 10px #0002}.editor[hidden],.validation[hidden]{display:none}.notice{position:absolute;bottom:22px;left:50%;transform:translateX(-50%);z-index:10;background:#293b2e;color:white;border-radius:8px;padding:9px 16px;max-width:85%;box-shadow:0 3px 18px #0003}.notice:empty{display:none}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.pages{position:absolute;inset:0;overflow:auto;background:#dbe0dc;display:none}.pages.active{display:block}.pages .print-page{transform-origin:top center}.context{position:absolute;z-index:15;min-width:180px;padding:5px;background:var(--grid-bg);color:var(--grid-fg);border:1px solid var(--grid-line);box-shadow:0 6px 30px #0003;border-radius:8px}.context button{display:block;width:100%;text-align:left;padding:7px 10px;color:inherit;border:0;background:none;font:12px system-ui;border-radius:4px}.context button:hover{background:var(--grid-head-active)}.context[hidden]{display:none}${printCSS.replaceAll('body{','._printbody{').replaceAll('*{box-sizing:border-box}','.pages *{box-sizing:border-box}')}`;
/** Framework-neutral spreadsheet presentation. Model state lives only in Workbook. */
export class GridWebElement extends Base {
  static get observedAttributes(){return['theme','readonly','view-mode','zoom','gridlines'];}
  constructor(){
    super();this.attachShadow({mode:'open'});this.shadowRoot.innerHTML=`<style>${styles}</style><div class="root" tabindex="0" role="grid" aria-label="Spreadsheet" aria-rowcount="${MAX_ROWS}" aria-colcount="${MAX_COLUMNS}"><div class="scroller" aria-hidden="true"><div class="spacer"></div></div><canvas class="canvas" aria-hidden="true"></canvas><textarea class="editor" spellcheck="false" hidden></textarea><select class="validation" hidden></select><div class="pages"></div><div class="notice" role="status" aria-live="polite"></div><div class="sr" id="accessible"></div><div class="context" hidden></div></div>`;
    for(const name of ['root','scroller','spacer','canvas','editor','validation','pages','notice','context'])this['_'+name]=this.shadowRoot.querySelector('.'+name);
    this._ctx=this._canvas.getContext('2d');this.SelectionChanged=new EventSource();this.CellEdited=new EventSource();this._selection={r1:0,c1:0,r2:0,c2:0};this._active={row:0,column:0};this._anchor={...this._active};this._zoom=1;this._viewMode='normal';this._theme='light';this._gridlines=true;this._readOnly=false;this._scheduled=0;this._connected=false;this._clipboard=null;this._subscriptions=[];this._chartRects=[];this._metrics={frames:0,visibleCells:0,renderMs:0};this._workbook=null;
    this._scroller.addEventListener('scroll',()=>this.Refresh());
    this._canvas.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();this.Zoom=this.Zoom+(e.deltaY<0?.1:-.1);}else{e.preventDefault();this._scroller.scrollTop+=e.deltaY;this._scroller.scrollLeft+=e.deltaX+(e.shiftKey?e.deltaY:0);}}, {passive:false});
    this._canvas.addEventListener('pointerdown',e=>this._pointerDown(e));this._canvas.addEventListener('pointermove',e=>this._pointerMove(e));this._canvas.addEventListener('pointerup',e=>this._pointerUp(e));this._canvas.addEventListener('pointercancel',()=>{this._drag=null;this._axesRevision=-1;this.Refresh();});
    this._canvas.addEventListener('dblclick',e=>{const hit=this._hit(e.offsetX,e.offsetY);if(hit.row>=0&&hit.column>=0)this.BeginEdit();});
    this._canvas.addEventListener('contextmenu',e=>{e.preventDefault();this._showContext(e.offsetX,e.offsetY);});
    this._root.addEventListener('keydown',e=>this._keyDown(e));this._root.addEventListener('copy',e=>this._copy(e));this._root.addEventListener('cut',e=>this._copy(e,true));this._root.addEventListener('paste',e=>this._paste(e));
    this._editor.addEventListener('compositionstart',()=>this._composing=true);this._editor.addEventListener('compositionend',()=>this._composing=false);
    this._editor.addEventListener('keydown',e=>{e.stopPropagation();if(e.isComposing||this._composing)return;if(e.key==='Escape'){e.preventDefault();this.CancelEdit();}else if((e.key==='Enter'&&!e.altKey)||e.key==='Tab'){e.preventDefault();if(this.CommitEdit())this._move(e.key==='Enter'?(e.shiftKey?-1:1):0,e.key==='Tab'?(e.shiftKey?-1:1):0);}});
    this._editor.addEventListener('blur',()=>{if(!this._editor.hidden&&!this._composing)this.CommitEdit(false);});this._validation.addEventListener('change',()=>{this._editor.value=this._validation.value;this.CommitEdit();});
    this._pages.addEventListener('dblclick',e=>{const td=e.target.closest('td[data-row]');if(!td||this.ReadOnly)return;this.Select(cellAddress(+td.dataset.row,+td.dataset.column),{scroll:false});td.contentEditable='true';td.textContent=String(this.ActiveCell.Input??'');td.focus();document.getSelection()?.selectAllChildren(td);});
    this._pages.addEventListener('focusout',e=>{const td=e.target.closest('td[contenteditable=true]');if(!td)return;td.contentEditable='false';this._try(()=>this.Sheet.GetCell(+td.dataset.row,+td.dataset.column).Input=td.textContent);this._renderPages();});
    this._pages.addEventListener('keydown',e=>{if(!e.target.isContentEditable)return;if(e.key==='Escape'){e.target.textContent=this.ActiveCell.Text;e.target.contentEditable='false';this._root.focus();}if(e.key==='Enter'&&!e.altKey){e.preventDefault();e.target.blur();}});
    this.Workbook=new Workbook();
  }
  connectedCallback(){this._connected=true;if(this._dataContext&&!this._vmSub)this.DataContext=this._dataContext;this._subscribe();this._resize=new ResizeObserver(()=>{this._axesRevision=-1;this.Refresh();});this._resize.observe(this);this.Refresh();}
  disconnectedCallback(){this._connected=false;this._vmSub?.Dispose();this._vmSub=null;this._resize?.disconnect();for(const s of this._subscriptions)s.Dispose();this._subscriptions=[];if(this._scheduled)cancelAnimationFrame(this._scheduled);this._scheduled=0;clearTimeout(this._noticeTimer);}
  attributeChangedCallback(name,old,value){if(old===value)return;if(name==='theme'){this._theme=value==='dark'?'dark':'light';this.Refresh();}if(name==='readonly')this._readOnly=value!==null;if(name==='view-mode')this.ViewMode=value;if(name==='zoom'){const n=Number(value);if(Number.isFinite(n)&&n>0)this.Zoom=n;}if(name==='gridlines'){this._gridlines=value!=='false';this.Refresh();}}
  get Workbook(){return this._workbook;}set Workbook(value){if(!(value instanceof Workbook))throw new TypeError('Workbook must be a GridWeb Workbook');for(const s of this._subscriptions)s.Dispose();this._subscriptions=[];this._workbook=value;this._sheet=value.ActiveWorksheet??value.Worksheets.Get(0);this._axesRevision=-1;this._subscribe();this.Refresh();}
  get workbook(){return this.Workbook;}set workbook(v){this.Workbook=v;}get Model(){return this.Workbook;}set Model(v){this.Workbook=v;}
  _subscribe(){if(!this._connected||this._subscriptions.length||!this._workbook)return;this._subscriptions.push(this._workbook.Changed.Subscribe(e=>{if(!this._workbook._sheets.includes(this._sheet))this._sheet=this._workbook.ActiveWorksheet;this._axesRevision=-1;this.Refresh();if(this.ViewMode==='pageLayout')this._renderPages();this.dispatchEvent(new CustomEvent('workbook-change',{detail:e,bubbles:true,composed:true}));}),this._workbook.Calculated.Subscribe(()=>{this._ruleCache=new Map();this.Refresh();}));}
  get Sheet(){return this._sheet;}set Sheet(value){if(typeof value==='string')value=this.Workbook.Worksheets.Get(value);if(!value||value.Workbook!==this.Workbook)throw new TypeError('Worksheet belongs to another workbook');if(!this.CommitEdit())return;this._sheet=value;this.Workbook.ActiveWorksheet=value;this._axesRevision=-1;this._scroller.scrollTop=this._scroller.scrollLeft=0;this.Select('A1');this._renderPages();}
  get Theme(){return this._theme;}set Theme(value){this.setAttribute('theme',value==='dark'?'dark':'light');}
  get Zoom(){return this._zoom;}set Zoom(value){this._zoom=Math.max(.25,Math.min(4,Number(value)||1));this._axesRevision=-1;this.Refresh();this.dispatchEvent(new CustomEvent('zoom-change',{detail:{zoom:this._zoom},bubbles:true,composed:true}));}
  get ViewMode(){return this._viewMode;}set ViewMode(value){if(!['normal','pageBreak','pageLayout'].includes(value))value='normal';this._viewMode=value;this._pages.classList.toggle('active',value==='pageLayout');if(value==='pageLayout')this._renderPages();this.Refresh();}
  get ReadOnly(){return this._readOnly;}set ReadOnly(v){this._readOnly=!!v;this._root.setAttribute('aria-readonly',String(!!v));}
  get ShowGridLines(){return this._gridlines;}set ShowGridLines(v){this._gridlines=!!v;this.Refresh();}
  get Selection(){return rangeAddress(this._selection);}set Selection(value){this.Select(value);}
  get SelectionRange(){return this.Sheet.GetRange(this._selection);}get ActiveCell(){return this.Sheet.GetCell(this._active.row,this._active.column);}
  get Metrics(){return{...this._metrics};}
  get DataContext(){return this._dataContext;}set DataContext(vm){this._vmSub?.Dispose();this._dataContext=vm;if(!vm)return;if(vm.Workbook)this.Workbook=vm.Workbook;if(vm.Selection)this.Select(vm.Selection);this._vmSub=vm.PropertyChanged?.Subscribe(e=>{if(e.PropertyName==='Selection'&&vm.Selection!==this.Selection)this.Select(vm.Selection);if(e.PropertyName==='Workbook'&&vm.Workbook!==this.Workbook)this.Workbook=vm.Workbook;});}
  Select(address,{scroll=true,extend=false}={}){
    if(!this._editor.hidden&&!this.CommitEdit())return;const ref=typeof address==='string'?parseRange(address):address;if(ref.sheet&&ref.sheet.toUpperCase()!==this.Sheet.Name.toUpperCase())this.Sheet=ref.sheet;
    const r=Math.max(0,Math.min(MAX_ROWS-1,ref.r1)),c=Math.max(0,Math.min(MAX_COLUMNS-1,ref.c1));this._active={row:r,column:c};
    if(extend){this._selection={r1:Math.min(this._anchor.row,r),c1:Math.min(this._anchor.column,c),r2:Math.max(this._anchor.row,r),c2:Math.max(this._anchor.column,c)};}
    else{this._anchor={row:r,column:c};this._selection={r1:r,c1:c,r2:Math.max(r,Math.min(MAX_ROWS-1,ref.r2??r)),c2:Math.max(c,Math.min(MAX_COLUMNS-1,ref.c2??c))};}
    this._selectedChart=null;this._context.hidden=true;if(scroll)this.ScrollIntoView(r,c);this.Refresh();const detail={address:this.Selection,bounds:{...this._selection},row:r,column:c,cell:this.ActiveCell,worksheet:this.Sheet};this.SelectionChanged.Emit(detail);this.dispatchEvent(new CustomEvent('selection-change',{detail,bubbles:true,composed:true}));if(this._dataContext&&this._dataContext.Selection!==this.Selection){if(this._dataContext.SetProperty)this._dataContext.SetProperty('Selection',this.Selection);else this._dataContext.Selection=this.Selection;}
  }
  _axes(){if(this._axesRevision===this.Workbook.Revision&&this._axesSheet===this.Sheet&&this._axesZoom===this.Zoom)return;const a=AxisLayout.ForSheet(this.Sheet);this._rows=a.rows;this._columns=a.columns;this._axesRevision=this.Workbook.Revision;this._axesSheet=this.Sheet;this._axesZoom=this.Zoom;const max=16000000;this._logicalHeight=this._rows.TotalSize*this.Zoom+28;this._logicalWidth=this._columns.TotalSize*this.Zoom+46;this._physicalHeight=Math.min(max,this._logicalHeight);this._physicalWidth=Math.min(max,this._logicalWidth);this._spacer.style.height=this._physicalHeight+'px';this._spacer.style.width=this._physicalWidth+'px';this._ruleCache=new Map();}
  _scroll(){this._axes();const h=this._scroller.clientHeight,w=this._scroller.clientWidth;return{x:this._scroller.scrollLeft*(this._logicalWidth-w)/Math.max(1,this._physicalWidth-w),y:this._scroller.scrollTop*(this._logicalHeight-h)/Math.max(1,this._physicalHeight-h)};}
  _setScroll(x,y){const h=this._scroller.clientHeight,w=this._scroller.clientWidth;this._scroller.scrollLeft=Math.max(0,x)*(this._physicalWidth-w)/Math.max(1,this._logicalWidth-w);this._scroller.scrollTop=Math.max(0,y)*(this._physicalHeight-h)/Math.max(1,this._logicalHeight-h);}
  ScrollIntoView(row,column){if(!this._connected)return;this._axes();const s=this._scroll(),w=this._scroller.clientWidth,h=this._scroller.clientHeight,z=this.Zoom,fx=this._columns.Offset(this.Sheet.FrozenColumns)*z,fy=this._rows.Offset(this.Sheet.FrozenRows)*z;let x=s.x,y=s.y;
    if(column>=this.Sheet.FrozenColumns){const a=this._columns.Offset(column)*z,b=this._columns.Offset(column+1)*z;if(a<x+fx)x=Math.max(0,a-fx);if(b>x+w-46)x=b-w+46;}
    if(row>=this.Sheet.FrozenRows){const a=this._rows.Offset(row)*z,b=this._rows.Offset(row+1)*z;if(a<y+fy)y=Math.max(0,a-fy);if(b>y+h-28)y=b-h+28;}
    this._setScroll(x,y);
  }
  _rect(row,column,r2=row,c2=column){const s=this._scroll(),z=this.Zoom;return{x:46+this._columns.Offset(column)*z-(column<this.Sheet.FrozenColumns?0:s.x),y:28+this._rows.Offset(row)*z-(row<this.Sheet.FrozenRows?0:s.y),width:(this._columns.Offset(c2+1)-this._columns.Offset(column))*z,height:(this._rows.Offset(r2+1)-this._rows.Offset(row))*z};}
  _hit(x,y){this._axes();const s=this._scroll(),z=this.Zoom,fx=46+this._columns.Offset(this.Sheet.FrozenColumns)*z,fy=28+this._rows.Offset(this.Sheet.FrozenRows)*z;let column=x<46?-1:this._columns.IndexAt((x-46+(x>=fx?s.x:0))/z),row=y<28?-1:this._rows.IndexAt((y-28+(y>=fy?s.y:0))/z);if(row>=0&&column>=0){const merge=this.Sheet._meta.merges.find(m=>contains(m,row,column));if(merge){row=merge.r1;column=merge.c1;}}return{row,column};}
  Refresh(){if(!this._connected||this._scheduled)return;this._scheduled=requestAnimationFrame(()=>{this._scheduled=0;this._render();});}
  _visible(axis,header,size,scroll,frozen){const z=this.Zoom,out=[];for(let i=0;i<frozen;i++){const length=axis.Size(i)*z;if(length)out.push({index:i,pos:header+axis.Offset(i)*z,size:length,frozen:true});}let i=Math.max(frozen,axis.IndexAt(axis.Offset(frozen)+scroll/z)),iterations=0;while(i<axis.Count&&iterations++<2000){const pos=header+axis.Offset(i)*z-scroll,length=axis.Size(i)*z;if(pos>=size)break;if(length)out.push({index:i,pos,size:length,frozen:false});i++;}return out;}
  _render(){
    if(!this._ctx||!this.Sheet||this.ViewMode==='pageLayout')return;const start=performance.now();this._axes();const w=this._scroller.clientWidth,h=this._scroller.clientHeight;if(w<1||h<1)return;const ratio=globalThis.devicePixelRatio||1;
    if(this._canvas.width!==Math.round(w*ratio)||this._canvas.height!==Math.round(h*ratio)){this._canvas.width=Math.round(w*ratio);this._canvas.height=Math.round(h*ratio);this._canvas.style.width=w+'px';this._canvas.style.height=h+'px';}
    const ctx=this._ctx;ctx.setTransform(ratio,0,0,ratio,0,0);const theme=getComputedStyle(this),bg=theme.getPropertyValue('--grid-bg').trim(),fg=theme.getPropertyValue('--grid-fg').trim(),line=theme.getPropertyValue('--grid-line').trim(),head=theme.getPropertyValue('--grid-head').trim(),active=theme.getPropertyValue('--grid-head-active').trim(),accent=theme.getPropertyValue('--grid-accent').trim();this._colors={bg,fg,line,head,active,accent};ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
    const scroll=this._scroll(),rows=this._visible(this._rows,28,h,scroll.y,this.Sheet.FrozenRows),cols=this._visible(this._columns,46,w,scroll.x,this.Sheet.FrozenColumns),fx=Math.min(w,46+this._columns.Offset(this.Sheet.FrozenColumns)*this.Zoom),fy=Math.min(h,28+this._rows.Offset(this.Sheet.FrozenRows)*this.Zoom);let count=0;
    for(const rf of [false,true])for(const cf of [false,true]){
      const left=cf?46:fx,top=rf?28:fy,right=cf?fx:w,bottom=rf?fy:h;if(right<=left||bottom<=top)continue;ctx.save();ctx.beginPath();ctx.rect(left,top,right-left,bottom-top);ctx.clip();const merged=new Set();
      for(const row of rows.filter(r=>r.frozen===rf))for(const col of cols.filter(c=>c.frozen===cf)){
        const m=this.Sheet._meta.merges.find(m=>contains(m,row.index,col.index));const r=m?m.r1:row.index,c=m?m.c1:col.index,id=r+':'+c;if(m&&merged.has(id))continue;if(m)merged.add(id);const rect=m?this._rect(m.r1,m.c1,m.r2,m.c2):{x:col.pos,y:row.pos,width:col.size,height:row.size};this._drawCell(ctx,r,c,rect);count++;
      }ctx.restore();
    }
    const selection=this._selection,rect=this._rect(selection.r1,selection.c1,selection.r2,selection.c2);ctx.save();ctx.beginPath();ctx.rect(46,28,w-46,h-28);ctx.clip();ctx.fillStyle=this.Theme==='dark'?'#52c18722':'#107c4112';ctx.fillRect(rect.x,rect.y,rect.width,rect.height);ctx.strokeStyle=accent;ctx.lineWidth=2;ctx.strokeRect(rect.x+1,rect.y+1,rect.width-2,rect.height-2);ctx.fillStyle=accent;ctx.fillRect(rect.x+rect.width-4,rect.y+rect.height-4,7,7);ctx.restore();
    this._chartRects=[];for(const chart of this.Sheet.Charts){const anchor=this._rect(chart.row,chart.column),r={x:anchor.x,y:anchor.y,width:chart.width*this.Zoom,height:chart.height*this.Zoom};if(r.x+r.width<46||r.y+r.height<28||r.x>w||r.y>h)continue;ctx.save();ctx.beginPath();ctx.rect(46,28,w-46,h-28);ctx.clip();drawChart(ctx,this.Sheet,chart,r,{dark:this.Theme==='dark',selected:chart.id===this._selectedChart});ctx.restore();this._chartRects.push({chart,...r});}
    if(this.ViewMode==='pageBreak'){ctx.save();ctx.setLineDash([6,4]);ctx.strokeStyle='#4481c3';ctx.lineWidth=2;try{const layout=paginate(this.Sheet),seen=new Set();for(const page of layout.pages){const row=page.rows.at(-1),col=page.columns.at(-1);if(row!=null&&!seen.has('r'+row)){seen.add('r'+row);const y=28+this._rows.Offset(row+1)*this.Zoom-scroll.y;ctx.beginPath();ctx.moveTo(46,y);ctx.lineTo(w,y);ctx.stroke();}if(col!=null&&!seen.has('c'+col)){seen.add('c'+col);const x=46+this._columns.Offset(col+1)*this.Zoom-scroll.x;ctx.beginPath();ctx.moveTo(x,28);ctx.lineTo(x,h);ctx.stroke();}}}catch{}ctx.restore();}
    ctx.font='11px system-ui';ctx.textBaseline='middle';ctx.lineWidth=1;
    for(const col of [...cols.filter(c=>!c.frozen),...cols.filter(c=>c.frozen)]){ctx.fillStyle=col.index>=selection.c1&&col.index<=selection.c2?active:head;ctx.fillRect(col.pos,0,col.size,28);ctx.strokeStyle=line;ctx.strokeRect(col.pos+.5,.5,col.size,27);ctx.fillStyle=fg;ctx.textAlign='center';ctx.fillText(columnName(col.index),col.pos+col.size/2,14,Math.max(1,col.size-4));}
    for(const row of [...rows.filter(r=>!r.frozen),...rows.filter(r=>r.frozen)]){ctx.fillStyle=row.index>=selection.r1&&row.index<=selection.r2?active:head;ctx.fillRect(0,row.pos,46,row.size);ctx.strokeStyle=line;ctx.strokeRect(.5,row.pos+.5,45,row.size);ctx.fillStyle=fg;ctx.textAlign='center';ctx.fillText(String(row.index+1),23,row.pos+row.size/2,42);if(this.Sheet._meta.rows[row.index]?.outline){ctx.fillStyle=accent;ctx.fillRect(0,row.pos,3,row.size);}}
    ctx.fillStyle=head;ctx.fillRect(0,0,46,28);ctx.fillStyle='#9aa99f';ctx.beginPath();ctx.moveTo(29,20);ctx.lineTo(38,11);ctx.lineTo(38,20);ctx.fill();
    ctx.strokeStyle='#8ba794';ctx.lineWidth=1.5;if(this.Sheet.FrozenRows){ctx.beginPath();ctx.moveTo(0,fy);ctx.lineTo(w,fy);ctx.stroke();}if(this.Sheet.FrozenColumns){ctx.beginPath();ctx.moveTo(fx,0);ctx.lineTo(fx,h);ctx.stroke();}
    this._metrics={frames:this._metrics.frames+1,visibleCells:count,renderMs:performance.now()-start};this._accessibility(rows,cols);this._positionEditor();
    this.dispatchEvent(new CustomEvent('grid-render',{detail:{metrics:this.Metrics,charts:this._chartRects.map(r=>({...r,chart:{...r.chart}}))}}));
  }
  _conditional(row,col,value,style){let result={...style},bar=null;
    for(const [index,rule]of this.Sheet._meta.conditionalFormats.entries()){
      if(!contains(rule.range,row,col))continue;
      if(rule.type==='cellValue'){if(criteriaPredicate(rule.criteria??(({lessThan:'<',lessThanOrEqual:'<=',greaterThan:'>',greaterThanOrEqual:'>=',equal:'=',notEqual:'<>'}[rule.operator]??'>')+String(rule.value??0)))(value))result={...result,...rule.style,font:{...result.font,...rule.style?.font}};}
      else if(rule.type==='formula'){const v=this.Workbook.Calculation.Evaluate(shiftFormula(rule.formula,row-rule.range.r1,col-rule.range.c1),{sheet:this.Sheet,row,col});if(!isError(v)&&truth(v))result={...result,...rule.style,font:{...result.font,...rule.style?.font}};}
      else{
        if(!this._ruleCache.has(index)){const values=[];for(const[n]of this.Sheet._cells){const r=Math.floor(n/MAX_COLUMNS),c=n%MAX_COLUMNS;if(contains(rule.range,r,c))values.push(this.Sheet.GetCell(r,c).Value);}const numbers=values.filter(v=>typeof v==='number'),counts=new Map();for(const v of values){const k=JSON.stringify([typeof v,typeof v==='string'?v.toUpperCase():v]);counts.set(k,(counts.get(k)??0)+1);}this._ruleCache.set(index,{min:numbers.length?numbers.reduce((a,b)=>Math.min(a,b)):0,max:numbers.length?numbers.reduce((a,b)=>Math.max(a,b)):1,counts});}
        const data=this._ruleCache.get(index),ratio=Math.max(0,Math.min(1,(Number(value)-data.min)/(data.max-data.min||1)));
        if(rule.type==='dataBar'&&typeof value==='number')bar={ratio:data.min>=0?value/(data.max||1):ratio,color:rule.color??'#21a366'};
        if(rule.type==='colorScale'&&typeof value==='number'){const low=parseHex(rule.minColor??'#fff2cc'),high=parseHex(rule.maxColor??'#63be7b');result.fill=`rgb(${low.map((v,i)=>Math.round(v+(high[i]-v)*ratio)).join(',')})`;}
        if(rule.type==='duplicate'&&(data.counts.get(JSON.stringify([typeof value,typeof value==='string'?value.toUpperCase():value]))??0)>1)result={...result,...(rule.style??{fill:'#fce4d6'})};
      }
    }return{style:result,bar};
  }
  _drawCell(ctx,row,col,rect){const cell=this.Sheet.GetCell(row,col),value=cell.Value,{x,y,width,height}=rect;let style=cell.Style;const table=this.Sheet._meta.tables.find(t=>contains(t.range,row,col));if(table)style={fill:row===table.range.r1?'#107c41':(row-table.range.r1)%2?this.Theme==='dark'?'#223d2c':'#edf5ef':this._colors.bg,...style,font:{...(row===table.range.r1?{bold:true,color:'#fff'}:{}),...style.font}};
    const conditional=this._conditional(row,col,value,style);style=conditional.style;ctx.save();ctx.beginPath();ctx.rect(x,y,width,height);ctx.clip();ctx.fillStyle=safeColor(style.fill,this._colors.bg);ctx.fillRect(x,y,width,height);if(conditional.bar){ctx.globalAlpha=.2;ctx.fillStyle=safeColor(conditional.bar.color,'#21a366');ctx.fillRect(x+2,y+3,Math.max(0,(width-4)*conditional.bar.ratio),height-6);ctx.globalAlpha=1;}
    if(this.ShowGridLines||table){ctx.strokeStyle=this._colors.line;ctx.lineWidth=.5;ctx.strokeRect(x+.25,y+.25,width,height);}if(style.border){ctx.strokeStyle=safeColor(style.border.color??'#82998a','#82998a');ctx.lineWidth=style.border.width??1;ctx.strokeRect(x+.5,y+.5,width-1,height-1);}
    const f=style.font??{},size=Math.max(6,Math.min(96,Number(f.size)||11))*this.Zoom*1.15;ctx.font=`${f.italic?'italic ':''}${f.bold?'600 ':''}${size}px ${String(f.name??'system-ui').replace(/[^\w ,\-]/g,'')}`;ctx.fillStyle=safeColor(f.color,this._colors.fg);ctx.textAlign=['left','center','right'].includes(style.horizontalAlignment)?style.horizontalAlignment:typeof value==='number'?'right':'left';ctx.textBaseline='middle';const tx=ctx.textAlign==='right'?x+width-6:ctx.textAlign==='center'?x+width/2:x+6,lineHeight=size*1.3;
    let lines=cell.Text.split('\n');if(style.wrapText){const wrapped=[];for(const line of lines){let current='';for(const word of line.split(' ')){if(current&&ctx.measureText(current+' '+word).width>width-10){wrapped.push(current);current=word;}else current+=(current?' ':'')+word;}wrapped.push(current);}lines=wrapped;}
    const total=lines.length*lineHeight,ty=style.verticalAlignment==='top'?y+lineHeight/2+3:style.verticalAlignment==='bottom'?y+height-total+lineHeight/2-3:y+height/2-total/2+lineHeight/2;
    lines.slice(0,30).forEach((line,i)=>ctx.fillText(line,tx,ty+i*lineHeight));if(f.underline||f.strikethrough){const length=Math.min(width-12,ctx.measureText(lines[0]??'').width),sx=ctx.textAlign==='right'?tx-length:ctx.textAlign==='center'?tx-length/2:tx;ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(sx,y+height/2+(f.underline?size*.55:0));ctx.lineTo(sx+length,y+height/2+(f.underline?size*.55:0));ctx.stroke();}
    if(cell.Comment){ctx.fillStyle='#bf4b4b';ctx.beginPath();ctx.moveTo(x+width-6,y);ctx.lineTo(x+width,y);ctx.lineTo(x+width,y+6);ctx.fill();}
    if(isError(value)){ctx.fillStyle='#107c41';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+6,y);ctx.lineTo(x,y+6);ctx.fill();}ctx.restore();
  }
  _accessibility(rows,cols){const holder=this.shadowRoot.getElementById('accessible'),fragment=document.createDocumentFragment();for(const r of rows.slice(0,12)){const row=document.createElement('div');row.setAttribute('role','row');row.setAttribute('aria-rowindex',String(r.index+1));for(const c of cols.slice(0,12)){const node=document.createElement('span');node.id=`aria-${r.index}-${c.index}`;node.setAttribute('role','gridcell');node.setAttribute('aria-colindex',String(c.index+1));node.setAttribute('aria-selected',String(contains(this._selection,r.index,c.index)));node.textContent=this.Sheet.GetCell(r.index,c.index).Text;row.append(node);}fragment.append(row);}const activeId=`aria-${this._active.row}-${this._active.column}`;if(!rows.slice(0,12).some(r=>r.index===this._active.row)||!cols.slice(0,12).some(c=>c.index===this._active.column)){const n=document.createElement('div');n.id=activeId;n.setAttribute('role','gridcell');n.setAttribute('aria-rowindex',String(this._active.row+1));n.setAttribute('aria-colindex',String(this._active.column+1));n.textContent=this.ActiveCell.Text;fragment.append(n);}holder.replaceChildren(fragment);this._root.setAttribute('aria-activedescendant',activeId);}
  _positionEditor(){if(this._editor.hidden)return;const r=this._rect(this._editCell.row,this._editCell.column),width=Math.max(100,Math.min(420,r.width));for(const node of [this._editor,this._validation])Object.assign(node.style,{left:Math.max(46,r.x)+'px',top:Math.max(28,r.y)+'px',width:width+'px',height:Math.max(26,r.height)+'px'});}
  BeginEdit(initial){if(this.ReadOnly||this.Sheet.IsProtected&&this.ActiveCell.Style.locked!==false){this.Notify('This cell is read-only.');return false;}this._editCell={...this._active};this._editor.hidden=false;this._editor.value=initial??String(this.ActiveCell.Input??'');this._editor.setAttribute('aria-label','Edit '+this.ActiveCell.Address);this._positionEditor();const rule=this.Sheet._meta.validations.find(v=>v.type==='list'&&contains(v.range,this._active.row,this._active.column));if(rule&&initial==null){this._validation.replaceChildren(...(rule.values??[]).map(v=>{const o=document.createElement('option');o.value=o.textContent=String(v);return o;}));this._validation.value=String(this.ActiveCell.Value??'');this._validation.hidden=false;this._validation.focus();}else{this._editor.focus();if(initial==null)this._editor.select();else this._editor.selectionStart=this._editor.selectionEnd=this._editor.value.length;}return true;}
  CommitEdit(focus=true){if(this._editor.hidden)return true;const p=this._editCell,value=this._editor.value;try{this.Sheet.GetCell(p.row,p.column).Input=value;this._editor.hidden=this._validation.hidden=true;if(focus)this._root.focus();const detail={worksheet:this.Sheet,row:p.row,column:p.column,value:this.Sheet.GetCell(p.row,p.column).Value,input:value};this.CellEdited.Emit(detail);this.dispatchEvent(new CustomEvent('cell-edit',{detail,bubbles:true,composed:true}));this.Refresh();return true;}catch(e){this.Notify(e.message);queueMicrotask(()=>this._editor.focus());return false;}}
  CancelEdit(){this._editor.hidden=this._validation.hidden=true;this._root.focus();this.Refresh();}
  _pointerDown(e){if(e.button!==0)return;this._context.hidden=true;if(!this.CommitEdit())return;this._root.focus();const hit=this._hit(e.offsetX,e.offsetY);
    for(const rect of (this.ChartHitTest?.(e.offsetX,e.offsetY)??this._chartRects.toReversed()))if(e.offsetX>=rect.x&&e.offsetX<=rect.x+rect.width&&e.offsetY>=rect.y&&e.offsetY<=rect.y+rect.height){this._selectedChart=rect.chart.id;this._drag={type:e.offsetX>rect.x+rect.width-12&&e.offsetY>rect.y+rect.height-12?'chartResize':'chart',x:e.offsetX,y:e.offsetY,chart:rect.chart};this._canvas.setPointerCapture(e.pointerId);this.dispatchEvent(new CustomEvent('chart-select',{detail:{chart:rect.chart},bubbles:true,composed:true}));this.Refresh();return;}
    if(e.offsetY<28&&hit.column>=0){const rect=this._rect(0,hit.column);if(Math.abs(e.offsetX-(rect.x+rect.width))<6){this._drag={type:'column',index:hit.column,start:e.clientX,size:this._columns.Size(hit.column)};this._canvas.setPointerCapture(e.pointerId);return;}}
    if(e.offsetX<46&&hit.row>=0){const rect=this._rect(hit.row,0);if(Math.abs(e.offsetY-(rect.y+rect.height))<6){this._drag={type:'row',index:hit.row,start:e.clientY,size:this._rows.Size(hit.row)};this._canvas.setPointerCapture(e.pointerId);return;}}
    const r=this._rect(this._selection.r1,this._selection.c1,this._selection.r2,this._selection.c2);if(Math.abs(e.offsetX-r.x-r.width)<8&&Math.abs(e.offsetY-r.y-r.height)<8&&!this.ReadOnly){this._drag={type:'fill',source:this.SelectionRange};this._canvas.setPointerCapture(e.pointerId);return;}
    if(hit.row<0&&hit.column<0)this.Select(this.Sheet.UsedRange.Address);else if(hit.row<0)this.Select({r1:0,c1:hit.column,r2:MAX_ROWS-1,c2:hit.column},{scroll:false});else if(hit.column<0)this.Select({r1:hit.row,c1:0,r2:hit.row,c2:MAX_COLUMNS-1},{scroll:false});else{this.Select(cellAddress(hit.row,hit.column),{extend:e.shiftKey,scroll:false});this._drag={type:'select'};this._canvas.setPointerCapture(e.pointerId);}
  }
  _pointerMove(e){const hit=this._hit(e.offsetX,e.offsetY);if(!this._drag){if(hit.row>=0&&hit.column>=0)this._canvas.title=this.Sheet.GetCell(hit.row,hit.column).Comment;this._canvas.style.cursor=hit.row<0?'default':hit.column<0?'default':'cell';return;}
    const d=this._drag;if(d.type==='column'||d.type==='row'){const size=Math.max(16,Math.min(1200,d.size+((d.type==='column'?e.clientX:e.clientY)-d.start)/this.Zoom));d.next=size;(d.type==='column'?this._columns:this._rows).SetSize(d.index,size);this.Refresh();}
    else if((d.type==='select'||d.type==='fill')&&hit.row>=0&&hit.column>=0){if(d.type==='select')this.Select(cellAddress(hit.row,hit.column),{extend:true,scroll:false});else{const b=d.source.Bounds;this._selection={r1:Math.min(b.r1,hit.row),c1:Math.min(b.c1,hit.column),r2:Math.max(b.r2,hit.row),c2:Math.max(b.c2,hit.column)};this.Refresh();}if(e.offsetY>this._scroller.clientHeight-20)this._scroller.scrollTop+=30;if(e.offsetX>this._scroller.clientWidth-20)this._scroller.scrollLeft+=30;}
  }
  _pointerUp(e){const d=this._drag;this._drag=null;if(this._canvas.hasPointerCapture(e.pointerId))this._canvas.releasePointerCapture(e.pointerId);if(!d)return;
    if(!this.ReadOnly)this._try(()=>{if(d.type==='column'&&d.next)this.Sheet.SetColumnWidth(d.index,d.next);if(d.type==='row'&&d.next)this.Sheet.SetRowHeight(d.index,d.next);if(d.type==='fill')d.source.AutoFill(this.SelectionRange);if(d.type==='chart'){const p=this._hit(e.offsetX,e.offsetY);if(p.row>=0&&p.column>=0)this.Sheet.UpdateChart(d.chart.id,{row:p.row,column:p.column});}if(d.type==='chartResize')this.Sheet.UpdateChart(d.chart.id,{width:d.chart.width+(e.offsetX-d.x)/this.Zoom,height:d.chart.height+(e.offsetY-d.y)/this.Zoom});});this._axesRevision=-1;this.Refresh();
  }
  _move(dr,dc,extend=false){let r=Math.max(0,Math.min(MAX_ROWS-1,this._active.row+dr)),c=Math.max(0,Math.min(MAX_COLUMNS-1,this._active.column+dc));this._axes();let guard=0;while(dr&&this._rows.Size(r)===0&&r>0&&r<MAX_ROWS-1&&guard++<100000)r+=Math.sign(dr);guard=0;while(dc&&this._columns.Size(c)===0&&c>0&&c<MAX_COLUMNS-1&&guard++<100000)c+=Math.sign(dc);this.Select(cellAddress(r,c),{extend});}
  _keyDown(e){if(e.target===this._editor||e.target===this._validation||e.target.isContentEditable)return;const mod=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();
    if(mod&&key==='z'){e.preventDefault();if(!this.ReadOnly)this._try(()=>e.shiftKey?this.Workbook.Redo():this.Workbook.Undo());return;}if(mod&&key==='y'){e.preventDefault();if(!this.ReadOnly)this.Workbook.Redo();return;}
    if(mod&&key==='a'){e.preventDefault();this.Select(this.Sheet.UsedRange.Address);return;}if(mod&&(key==='b'||key==='i')){e.preventDefault();if(!this.ReadOnly){const k=key==='b'?'bold':'italic';this._try(()=>this.SelectionRange.SetStyle({font:{[k]:!this.ActiveCell.Style.font?.[k]}}));}return;}
    const arrows={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};if(arrows[e.key]){e.preventDefault();const[dr,dc]=arrows[e.key];if(mod){const b=this.Sheet.UsedRange.Bounds;this.Select(cellAddress(dr<0?0:dr>0?b.r2:this._active.row,dc<0?0:dc>0?b.c2:this._active.column),{extend:e.shiftKey});}else this._move(dr,dc,e.shiftKey);return;}
    if(e.key==='Home'){e.preventDefault();this.Select(cellAddress(mod?0:this._active.row,0),{extend:e.shiftKey});return;}if(e.key==='End'&&mod){e.preventDefault();const b=this.Sheet.UsedRange.Bounds;this.Select(cellAddress(b.r2,b.c2),{extend:e.shiftKey});return;}
    if(e.key==='PageDown'||e.key==='PageUp'){e.preventDefault();this._move((e.key==='PageDown'?1:-1)*Math.max(1,Math.floor(this._scroller.clientHeight/(24*this.Zoom))-2),0,e.shiftKey);return;}
    if(e.key==='Tab'){e.preventDefault();this._move(0,e.shiftKey?-1:1);return;}if(e.key==='Enter'||e.key==='F2'){e.preventDefault();this.BeginEdit();return;}
    if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();if(!this.ReadOnly)this._try(()=>this._selectedChart?this.Sheet.RemoveChart(this._selectedChart):this.SelectionRange.Clear('contents'));return;}
    if(e.key==='Escape'){this._context.hidden=true;return;}if(e.key.length===1&&!mod&&!e.altKey){e.preventDefault();this.BeginEdit(e.key);}
  }
  _copy(e,cut=false){if(e.target===this._editor||e.target.isContentEditable)return;this._try(()=>{const range=this.SelectionRange,text=toDelimited(range,{delimiter:'\t',safe:false});this._clipboard=this._captureClipboard(range,text,cut);e.clipboardData?.setData('text/plain',text);e.preventDefault();if(cut&&!this.ReadOnly){this._clipboard.values=range._read('Input');this._clipboard.styles=range._read('Style');range.Clear('contents');}});}
  _paste(e){if(e.target===this._editor||e.target.isContentEditable||this.ReadOnly)return;const text=e.clipboardData?.getData('text/plain');if(text==null)return;e.preventDefault();this.PasteText(text);}
  _captureClipboard(range,text,cut=false){return{text,cut,bounds:{...range.Bounds},records:Array.from({length:range.RowCount},(_,r)=>Array.from({length:range.ColumnCount},(_,c)=>structuredClone(range.GetCell(r,c)._record??{})))};}
  PasteText(text){if(this.ReadOnly)return;this._try(()=>{if(this._clipboard?.text===text){const clip=this._clipboard,target=this.Sheet.GetRange(this.ActiveCell.Address).Resize(clip.records.length,clip.records[0].length);this.Workbook.Transaction('Paste cells',()=>clip.records.forEach((row,r)=>row.forEach((record,c)=>{const cell=target.GetCell(r,c),input=record.input??null;const value=!record.literal&&typeof input==='string'&&input.startsWith('=')&&!clip.cut?shiftFormula(input,target.Bounds.r1-clip.bounds.r1,target.Bounds.c1-clip.bounds.c1):input;if(record.literal)cell.Value=value;else cell.Input=value;cell.Style=record.style??{};cell.Comment=record.comment??'';})));if(clip.cut)this._clipboard=null;this.Select(target.Address);}else{const range=importDelimited(this.Sheet,text,{address:this.ActiveCell.Address,delimiter:'\t',allowFormulas:true});if(range)this.Select(range.Address);}});}
  async CopySelection(){const text=toDelimited(this.SelectionRange,{delimiter:'\t',safe:false});this._clipboard=this._captureClipboard(this.SelectionRange,text,false);if(navigator.clipboard)await navigator.clipboard.writeText(text);return text;}
  async Paste(){try{this.PasteText(await navigator.clipboard.readText());}catch{this.Notify('Use Ctrl+V or Command+V to paste from the clipboard.');}}
  _showContext(x,y){const menu=this._context;menu.replaceChildren();const actions=[['Copy',()=>this.CopySelection()],['Paste',()=>this.Paste()],['Clear contents',()=>this.SelectionRange.Clear('contents')],['Insert row above',()=>this.Sheet.InsertRows(this._active.row)],['Delete row',()=>this.Sheet.DeleteRows(this._active.row)],['Insert column left',()=>this.Sheet.InsertColumns(this._active.column)],['Delete column',()=>this.Sheet.DeleteColumns(this._active.column)],['Autofit columns',()=>this.SelectionRange.Format.AutoFitColumns()],['Merge cells',()=>this.SelectionRange.Merge()],['Unmerge cells',()=>this.SelectionRange.Unmerge()]];for(const[label,action]of actions){const b=document.createElement('button');b.textContent=label;b.disabled=this.ReadOnly&&label!=='Copy';b.addEventListener('click',()=>{menu.hidden=true;this._try(action);});menu.append(b);}menu.style.left=Math.min(x,this.clientWidth-195)+'px';menu.style.top=Math.min(y,Math.max(0,this.clientHeight-350))+'px';menu.hidden=false;}
  _renderPages(){if(this.ViewMode!=='pageLayout'||!this.Sheet)return;this._try(()=>this._pages.innerHTML=printPagesHTML(this.Sheet));}
  Print(){try{const popup=window.open('','_blank');if(!popup){this.Notify('Allow pop-ups to open the print preview.');return;}popup.document.open();popup.document.write(createPrintDocument(this.Sheet));popup.document.close();popup.focus();popup.print();}catch(e){this.Notify(e.message);}}
  Notify(message){this._notice.textContent=String(message);clearTimeout(this._noticeTimer);this._noticeTimer=setTimeout(()=>this._notice.textContent='',5000);this.dispatchEvent(new CustomEvent('grid-error',{detail:{message:String(message)},bubbles:true,composed:true}));}
  _try(action){try{const result=action();if(result?.catch)result.catch(e=>this.Notify(e.message));return result;}catch(e){this.Notify(e.message);return undefined;}}
  Focus(){this._root.focus();}
  Dispose(){this.disconnectedCallback();this._vmSub?.Dispose();this.SelectionChanged.Clear();this.CellEdited.Clear();}
}
function parseHex(value){const h=/^#([0-9a-f]{6})$/i.exec(value)?.[1]??'ffffff';return[0,2,4].map(i=>parseInt(h.slice(i,i+2),16));}
export function defineGridWeb(name='grid-web'){if(globalThis.customElements&&!customElements.get(name))customElements.define(name,GridWebElement);return GridWebElement;}
defineGridWeb();
