import { Workbook } from './model.js';
import { isError } from './errors.js';
import { MAX_COLUMNS, MAX_OPERATION_CELLS, cellAddress, parseCell, parseRange, rangeAddress, quoteSheet, shiftFormula } from './address.js';
import { writeZip, readZip } from './zip.js';
import { xmlEscape as x, parseXML, child, children, descendants, allText } from './xml.js';
import { chartData } from './charts.js';
export { toDelimited as exportCSV, importDelimited as importCSV, parseDelimited } from './data.js';
const XML='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
const NS='http://schemas.openxmlformats.org/spreadsheetml/2006/main',REL='http://schemas.openxmlformats.org/officeDocument/2006/relationships',PKG='http://schemas.openxmlformats.org/package/2006/relationships';
const relationship=(id,type,target)=>`<Relationship Id="${x(id)}" Type="${REL}/${type}" Target="${x(target)}"/>`;
const relationships=items=>XML+`<Relationships xmlns="${PKG}">${items.join('')}</Relationships>`;
const rgb=value=>/^#[\da-f]{6}$/i.test(value??'')?'FF'+value.slice(1).toUpperCase():/^#[\da-f]{3}$/i.test(value??'')?'FF'+value.slice(1).split('').map(c=>c+c).join('').toUpperCase():null;
const color=node=>node?.attrs.rgb?'#'+node.attrs.rgb.slice(-6):undefined;
const normalizePath=(base,target)=>{if(target.startsWith('/'))return target.slice(1);const parts=base.split('/').slice(0,-1);for(const p of target.split('/')){if(p==='..')parts.pop();else if(p!=='.')parts.push(p);}return parts.join('/');};
const relPath=path=>path.slice(0,path.lastIndexOf('/')+1)+'_rels/'+path.slice(path.lastIndexOf('/')+1)+'.rels';
function fontXML(font={}){return `<font>${font.bold?'<b/>':''}${font.italic?'<i/>':''}${font.underline?'<u/>':''}${font.strikethrough?'<strike/>':''}<sz val="${Math.max(6,Math.min(96,+font.size||11))}"/><name val="${x(font.name??'Calibri')}"/>${rgb(font.color)?`<color rgb="${rgb(font.color)}"/>`:''}</font>`;}
function fillXML(fill){return rgb(fill)?`<fill><patternFill patternType="solid"><fgColor rgb="${rgb(fill)}"/><bgColor indexed="64"/></patternFill></fill>`:'<fill><patternFill patternType="none"/></fill>';}
function borderXML(border){return `<border>${['left','right','top','bottom'].map(side=>border?`<${side} style="thin"><color rgb="${rgb(border.color)??'FF82998A'}"/></${side}>`:`<${side}/>`).join('')}<diagonal/></border>`;}
function stylePart(styles,dxfs){
  const formats=new Map();for(const s of styles)if(s.numberFormat&&s.numberFormat!=='General'&&!formats.has(s.numberFormat))formats.set(s.numberFormat,164+formats.size);
  const numFmts=`<numFmts count="${formats.size}">${[...formats].map(([f,id])=>`<numFmt numFmtId="${id}" formatCode="${x(f)}"/>`).join('')}</numFmts>`;
  return XML+`<styleSheet xmlns="${NS}">${numFmts}<fonts count="${styles.length}">${styles.map(s=>fontXML(s.font)).join('')}</fonts><fills count="${styles.length+2}"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill>${styles.map(s=>fillXML(s.fill)).join('')}</fills><borders count="${styles.length}">${styles.map(s=>borderXML(s.border)).join('')}</borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="${styles.length}">${styles.map((s,i)=>`<xf numFmtId="${formats.get(s.numberFormat)??0}" fontId="${i}" fillId="${rgb(s.fill)?i+2:0}" borderId="${i}" xfId="0" applyNumberFormat="1" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"${s.locked===false?' applyProtection="1"':''}><alignment horizontal="${x(s.horizontalAlignment??'general')}" vertical="${x(s.verticalAlignment??'center')}" wrapText="${s.wrapText?1:0}"/>${s.locked===false?'<protection locked="0"/>':''}</xf>`).join('')}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><dxfs count="${dxfs.length}">${dxfs.map(s=>`<dxf>${s.font?fontXML(s.font):''}${s.fill?fillXML(s.fill):''}${s.border?borderXML(s.border):''}</dxf>`).join('')}</dxfs><tableStyles count="0" defaultTableStyle="TableStyleMedium4" defaultPivotStyle="PivotStyleLight16"/></styleSheet>`;
}
function conditionalXML(rule,dxf,index){
  let content='',attrs=`priority="${index+1}"`;
  if(rule.type==='dataBar')content=`<cfRule type="dataBar" ${attrs}><dataBar><cfvo type="min"/><cfvo type="max"/><color rgb="${rgb(rule.color)??'FF21A366'}"/></dataBar></cfRule>`;
  else if(rule.type==='colorScale')content=`<cfRule type="colorScale" ${attrs}><colorScale><cfvo type="min"/><cfvo type="max"/><color rgb="${rgb(rule.minColor)??'FFFFF2CC'}"/><color rgb="${rgb(rule.maxColor)??'FF63BE7B'}"/></colorScale></cfRule>`;
  else if(rule.type==='formula')content=`<cfRule type="expression" dxfId="${dxf}" ${attrs}><formula>${x(String(rule.formula).replace(/^=/,''))}</formula></cfRule>`;
  else if(rule.type==='duplicate')content=`<cfRule type="duplicateValues" dxfId="${dxf}" ${attrs}/>`;
  else{const m=/^(<=|>=|<>|=|<|>)?(.*)$/.exec(String(rule.criteria??(({lessThan:'<',lessThanOrEqual:'<=',greaterThan:'>',greaterThanOrEqual:'>=',equal:'=',notEqual:'<>'}[rule.operator]??'>')+String(rule.value??0)))),ops={'=':'equal','<>':'notEqual','>':'greaterThan','<':'lessThan','>=':'greaterThanOrEqual','<=':'lessThanOrEqual'},v=m[2];content=`<cfRule type="cellIs" operator="${ops[m[1]??'=']}" dxfId="${dxf}" ${attrs}><formula>${x(Number.isFinite(Number(v))?v:'"'+v.replace(/"/g,'""')+'"')}</formula></cfRule>`;}
  return`<conditionalFormatting sqref="${x(rangeAddress(rule.range))}">${content}</conditionalFormatting>`;
}
function validationXML(rule){const type={list:'list',number:'decimal',whole:'whole',date:'date',textLength:'textLength',custom:'custom'}[rule.type];let a='',b='',operator='between';if(rule.type==='list')a='"'+(rule.values??[]).join(',')+'"';else if(rule.type==='custom')a=String(rule.formula??'').replace(/^=/,'').replace(/\bVALUE\b/g,cellAddress(rule.range.r1,rule.range.c1));else{a=rule.min??rule.max??0;b=rule.max??'';if(rule.min==null)operator='lessThanOrEqual';else if(rule.max==null)operator='greaterThanOrEqual';}return`<dataValidation type="${type}" operator="${operator}" allowBlank="${rule.allowBlank===false?0:1}" showErrorMessage="1" errorStyle="stop" error="${x(rule.message??'Invalid value')}" sqref="${x(rangeAddress(rule.range))}"><formula1>${x(a)}</formula1>${b!==''?`<formula2>${x(b)}</formula2>`:''}</dataValidation>`;}
function chartXML(sheet,chart){
  const data=chartData(sheet,chart),q=quoteSheet(sheet.Name),r=chart.range,end=Math.min(r.r2,r.r1+200),first=r.r1+1;
  const strCache=values=>`<c:strCache><c:ptCount val="${values.length}"/>${values.map((v,i)=>`<c:pt idx="${i}"><c:v>${x(v)}</c:v></c:pt>`).join('')}</c:strCache>`;
  const numCache=values=>`<c:numCache><c:formatCode>General</c:formatCode><c:ptCount val="${values.length}"/>${values.map((v,i)=>v==null?'':`<c:pt idx="${i}"><c:v>${Number(v)||0}</c:v></c:pt>`).join('')}</c:numCache>`;
  const series=data.series.map((s,i)=>{const col=r.c1+1+i,f=`${q}!${cellAddress(first,col)}:${cellAddress(end,col)}`,cat=`${q}!${cellAddress(first,r.c1)}:${cellAddress(end,r.c1)}`;return`<c:ser><c:idx val="${i}"/><c:order val="${i}"/><c:tx><c:strRef><c:f>${x(q+'!'+cellAddress(r.r1,col))}</c:f>${strCache([s.name])}</c:strRef></c:tx>${chart.type==='scatter'?`<c:xVal><c:numRef><c:f>${x(cat)}</c:f>${numCache(data.labels.map(Number))}</c:numRef></c:xVal><c:yVal><c:numRef><c:f>${x(f)}</c:f>${numCache(s.values)}</c:numRef></c:yVal>`:`<c:cat><c:strRef><c:f>${x(cat)}</c:f>${strCache(data.labels)}</c:strRef></c:cat><c:val><c:numRef><c:f>${x(f)}</c:f>${numCache(s.values)}</c:numRef></c:val>`}</c:ser>`;}).join('');
  const type=chart.type==='column'||chart.type==='bar'?'barChart':chart.type+'Chart';let options=type==='barChart'?`<c:barDir val="${chart.type==='bar'?'bar':'col'}"/><c:grouping val="clustered"/>`:type==='lineChart'||type==='areaChart'?'<c:grouping val="standard"/>':type==='scatterChart'?'<c:scatterStyle val="lineMarker"/>':'';
  const axisIds=type==='pieChart'?'':'<c:axId val="100"/><c:axId val="200"/>';
  const axes=type==='pieChart'?'':`<c:${type==='scatterChart'?'valAx':'catAx'}><c:axId val="100"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="${chart.type==='bar'?'l':'b'}"/><c:crossAx val="200"/><c:crosses val="autoZero"/></c:${type==='scatterChart'?'valAx':'catAx'}><c:valAx><c:axId val="200"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="${chart.type==='bar'?'b':'l'}"/><c:majorGridlines/><c:numFmt formatCode="General" sourceLinked="1"/><c:crossAx val="100"/><c:crosses val="autoZero"/><c:crossBetween val="between"/></c:valAx>`;
  return XML+`<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL}"><c:chart><c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>${x(chart.title)}</a:t></a:r></a:p></c:rich></c:tx></c:title><c:plotArea><c:layout/><c:${type}>${options}<c:varyColors val="${type==='pieChart'?1:0}"/>${series}${axisIds}</c:${type}>${axes}</c:plotArea><c:legend><c:legendPos val="b"/></c:legend><c:plotVisOnly val="1"/><c:dispBlanksAs val="gap"/></c:chart></c:chartSpace>`;
}
/** Creates a real OOXML .xlsx package with values, formulas, styles, tables and charts. */
export function exportXlsx(book,{onWarning=()=>{}}={}){
  book.Calculate();const files={},types=[],styles=[{}],styleIds=new Map([['{}',0]]),dxfs=[],sheetRels=[],workbookRels=[];let chartId=0,tableId=0;
  const addType=(path,type)=>types.push(`<Override PartName="/${path}" ContentType="application/vnd.openxmlformats-officedocument.${type}+xml"/>`);
  for(const [si,sheet]of book._sheets.entries()){
    const rels=[],rows=new Map(),records=new Map(sheet._cells);
    for(const[key,spill]of book.Calculation.spills)if(key.startsWith(sheet.Id+':')){const p=parseCell(key.slice(sheet.Id.length+1));const n=p.row*MAX_COLUMNS+p.column;if(!records.get(n)?.input)records.set(n,{...records.get(n),input:isError(spill.value)?{error:spill.value.code}:spill.value,literal:typeof spill.value==='string',style:records.get(n)?.style??{}});}
    for(const[n,record]of [...records].sort((a,b)=>a[0]-b[0])){
      const row=Math.floor(n/MAX_COLUMNS),col=n%MAX_COLUMNS,cell=sheet.GetCell(row,col),style=record.style??{},signature=JSON.stringify(style);let styleId=styleIds.get(signature);if(styleId==null){styleId=styles.length;styles.push(style);styleIds.set(signature,styleId);}
      const formula=cell.Formula,value=cell.Value,address=cell.Address,arr=book.Calculation.arrays.get(sheet.Id+':'+address);let f=formula?`<f${arr?` t="array" ref="${address}:${cellAddress(row+arr.length-1,col+arr[0].length-1)}"`:''}>${x(formula.slice(1))}</f>`:'',type='',v='';
      if(isError(value)){type=' t="e"';v=`<v>${x(value.code==='#CIRC!'?'#REF!':value.code)}</v>`;}
      else if(typeof value==='number'){v=`<v>${value}</v>`;}
      else if(typeof value==='boolean'){type=' t="b"';v=`<v>${value?1:0}</v>`;}
      else if(value!=null){if(formula){type=' t="str"';v=`<v>${x(value)}</v>`;}else{type=' t="inlineStr"';v=`<is><t xml:space="preserve">${x(value)}</t></is>`;}}
      if(!rows.has(row))rows.set(row,[]);rows.get(row).push(`<c r="${address}" s="${styleId}"${type}>${f}${v}</c>`);
    }
    for(const row of Object.keys(sheet._meta.rows))if(!rows.has(+row))rows.set(+row,[]);
    const cols=Object.entries(sheet._meta.columns).map(([i,v])=>`<col min="${+i+1}" max="${+i+1}" width="${((v.size??100)-5)/7}" customWidth="1"${v.hidden?' hidden="1"':''}/>`).join('');
    const data=[...rows].sort((a,b)=>a[0]-b[0]).map(([row,cells])=>{const m=sheet._meta.rows[row];return`<row r="${row+1}"${m?.size?` ht="${m.size*.75}" customHeight="1"`:''}${m?.hidden||sheet._filtered.has(row)?' hidden="1"':''}${m?.outline?` outlineLevel="${m.outline}"`:''}>${cells.join('')}</row>`;}).join('');
    const fr=sheet.FrozenRows,fc=sheet.FrozenColumns,pane=fr||fc?`<pane${fc?` xSplit="${fc}"`:''}${fr?` ySplit="${fr}"`:''} topLeftCell="${cellAddress(fr,fc)}" activePane="${fr&&fc?'bottomRight':fr?'bottomLeft':'topRight'}" state="frozen"/>`:'';
    const merges=sheet.MergedRanges.length?`<mergeCells count="${sheet.MergedRanges.length}">${sheet.MergedRanges.map(m=>`<mergeCell ref="${rangeAddress(m)}"/>`).join('')}</mergeCells>`:'';
    let conditional='';for(const rule of sheet._meta.conditionalFormats){const dxf=dxfs.length;dxfs.push(rule.style??{});conditional+=conditionalXML(rule,dxf,dxfs.length-1);}
    const validations=sheet._meta.validations.length?`<dataValidations count="${sheet._meta.validations.length}">${sheet._meta.validations.map(validationXML).join('')}</dataValidations>`:'';
    const filter=sheet._meta.filter?`<autoFilter ref="${rangeAddress(sheet._meta.filter.range)}">${sheet._meta.filter.criteria.map(c=>{const m=/^(<=|>=|<>|=|<|>)?(.*)$/.exec(String(c.value)),op={"=":"equal","<>":"notEqual",">":"greaterThan","<":"lessThan",">=":"greaterThanOrEqual","<=":"lessThanOrEqual"}[m[1]??"="];return `<filterColumn colId="${c.column}"><customFilters><customFilter operator="${op}" val="${x(m[2])}"/></customFilters></filterColumn>`;}).join('')}</autoFilter>`:'';
    const tables=sheet.Tables.map(table=>{
      const id=++tableId,path=`xl/tables/table${id}.xml`,r=table.range,headers=sheet.GetRange({...r,r2:r.r1}).Values[0];rels.push(relationship('table'+id,'table',`../tables/table${id}.xml`));addType(path,'spreadsheetml.table');
      files[path]=XML+`<table xmlns="${NS}" id="${id}" name="${x(table.name)}" displayName="${x(table.name)}" ref="${rangeAddress(r)}" totalsRowShown="0"><autoFilter ref="${rangeAddress(r)}"/><tableColumns count="${headers.length}">${headers.map((h,i)=>`<tableColumn id="${i+1}" name="${x(h??'Column'+(i+1))}"/>`).join('')}</tableColumns><tableStyleInfo name="TableStyleMedium4" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/></table>`;return`<tablePart r:id="table${id}"/>`;
    });
    let drawing='';if(sheet.Charts.length){const anchors=[],dr=[];for(const chart of sheet.Charts){const id=++chartId,path=`xl/charts/chart${id}.xml`;files[path]=chartXML(sheet,chart);addType(path,'drawingml.chart');dr.push(relationship('chart'+id,'chart',`../charts/chart${id}.xml`));if(chartData(sheet,chart).truncated)onWarning(`Chart ${chart.title}: the exported plot is limited to the first 200 rows / 8 series.`);anchors.push(`<xdr:oneCellAnchor><xdr:from><xdr:col>${chart.column}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${chart.row}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx="${Math.round(chart.width*9525)}" cy="${Math.round(chart.height*9525)}"/><xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="${id}" name="${x(chart.title)}"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" r:id="chart${id}"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:oneCellAnchor>`);}
      const path=`xl/drawings/drawing${si+1}.xml`;files[path]=XML+`<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL}">${anchors.join('')}</xdr:wsDr>`;files[relPath(path)]=relationships(dr);addType(path,'drawing');rels.push(relationship('drawing','drawing',`../drawings/drawing${si+1}.xml`));drawing='<drawing r:id="drawing"/>';
    }
    let notes='';const comments=[...sheet._cells].filter(([,v])=>v.comment);if(comments.length){const path=`xl/comments${si+1}.xml`;files[path]=XML+`<comments xmlns="${NS}"><authors><author>GridWeb</author></authors><commentList>${comments.map(([n,v])=>`<comment ref="${cellAddress(Math.floor(n/MAX_COLUMNS),n%MAX_COLUMNS)}" authorId="0"><text><t xml:space="preserve">${x(v.comment)}</t></text></comment>`).join('')}</commentList></comments>`;addType(path,'spreadsheetml.comments');rels.push(relationship('comments','comments',`../comments${si+1}.xml`));
      const vml=`xl/drawings/comments${si+1}.vml`;files[vml]=`<xml xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><o:shapelayout v:ext="edit"><o:idmap v:ext="edit" data="1"/></o:shapelayout><v:shapetype id="_x0000_t202" coordsize="21600,21600" o:spt="202" path="m,l,21600r21600,l21600,xe"><v:stroke joinstyle="miter"/><v:path gradientshapeok="t" o:connecttype="rect"/></v:shapetype>${comments.map(([n],i)=>`<v:shape id="_x0000_s${1025+i}" type="#_x0000_t202" style="position:absolute;width:144pt;height:79pt;visibility:hidden" fillcolor="#ffffe1"><v:fill color2="#ffffe1"/><v:shadow on="t" color="black" obscured="t"/><v:path o:connecttype="none"/><v:textbox><div style="text-align:left"/></v:textbox><x:ClientData ObjectType="Note"><x:MoveWithCells/><x:SizeWithCells/><x:AutoFill>False</x:AutoFill><x:Row>${Math.floor(n/MAX_COLUMNS)}</x:Row><x:Column>${n%MAX_COLUMNS}</x:Column></x:ClientData></v:shape>`).join('')}</xml>`;rels.push(relationship('notes','vmlDrawing',`../drawings/comments${si+1}.vml`));notes='<legacyDrawing r:id="notes"/>';
    }
    const path=`xl/worksheets/sheet${si+1}.xml`;files[path]=XML+`<worksheet xmlns="${NS}" xmlns:r="${REL}"><dimension ref="${sheet.UsedRange.Address}"/><sheetViews><sheetView workbookViewId="0">${pane}</sheetView></sheetViews><sheetFormatPr defaultRowHeight="18"/>${cols?`<cols>${cols}</cols>`:''}<sheetData>${data}</sheetData>${sheet.IsProtected?'<sheetProtection sheet="1" objects="1" scenarios="1"/>':''}${filter}${merges}${conditional}${validations}<pageMargins left="0.4" right="0.4" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup paperSize="${sheet._meta.print.paper==='Letter'?1:9}" orientation="${sheet._meta.print.orientation}" scale="${Math.round(sheet._meta.print.scale*100)}"/>${drawing}${notes}${tables.length?`<tableParts count="${tables.length}">${tables.join('')}</tableParts>`:''}</worksheet>`;if(rels.length)files[relPath(path)]=relationships(rels);addType(path,'spreadsheetml.worksheet');workbookRels.push(relationship('sheet'+(si+1),'worksheet',`worksheets/sheet${si+1}.xml`));
  }
  const defined=[...book._names].map(([name,value])=>`<definedName name="${x(name)}">${x(typeof value==='string'&&value.startsWith('=')?value.slice(1):typeof value==='string'?'"'+value.replace(/"/g,'""')+'"':value)}</definedName>`);
  book._sheets.forEach((s,i)=>{if(s._meta.print.area)defined.push(`<definedName name="_xlnm.Print_Area" localSheetId="${i}">${x(quoteSheet(s.Name)+'!'+rangeAddress(s._meta.print.area))}</definedName>`);if(s._meta.print.repeatRows)defined.push(`<definedName name="_xlnm.Print_Titles" localSheetId="${i}">${x(quoteSheet(s.Name)+'!$1:$'+s._meta.print.repeatRows)}</definedName>`);});
  files['xl/workbook.xml']=XML+`<workbook xmlns="${NS}" xmlns:r="${REL}"><workbookPr date1904="0"/><bookViews><workbookView activeTab="${Math.max(0,book._sheets.indexOf(book.ActiveWorksheet))}"/></bookViews><sheets>${book._sheets.map((s,i)=>`<sheet name="${x(s.Name)}" sheetId="${i+1}" r:id="sheet${i+1}"/>`).join('')}</sheets>${defined.length?`<definedNames>${defined.join('')}</definedNames>`:''}<calcPr calcId="191029" fullCalcOnLoad="1" forceFullCalc="1"/></workbook>`;
  files['xl/styles.xml']=stylePart(styles,dxfs);workbookRels.push(relationship('styles','styles','styles.xml'));files['xl/_rels/workbook.xml.rels']=relationships(workbookRels);files['_rels/.rels']=relationships([relationship('officeDocument','officeDocument','xl/workbook.xml')]);addType('xl/workbook.xml','spreadsheetml.sheet.main');addType('xl/styles.xml','spreadsheetml.styles');
  files['[Content_Types].xml']=XML+`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="vml" ContentType="application/vnd.openxmlformats-officedocument.vmlDrawing"/>${types.join('')}</Types>`;
  return writeZip(files);
}
const builtins={0:'General',1:'0',2:'0.00',3:'#,##0',4:'#,##0.00',9:'0%',10:'0.00%',11:'0.00E+00',14:'mm-dd-yy',15:'d-mmm-yy',16:'d-mmm',17:'mmm-yy',18:'h:mm AM/PM',19:'h:mm:ss AM/PM',20:'h:mm',21:'h:mm:ss',22:'m/d/yy h:mm',37:'#,##0;(#,##0)',38:'#,##0;[Red](#,##0)',39:'#,##0.00;(#,##0.00)',40:'#,##0.00;[Red](#,##0.00)',49:'@'};
function readFont(node){if(!node)return{};const f={};if(child(node,'b'))f.bold=true;if(child(node,'i'))f.italic=true;if(child(node,'u'))f.underline=true;if(child(node,'strike'))f.strikethrough=true;if(child(node,'sz'))f.size=+child(node,'sz').attrs.val;if(child(node,'name'))f.name=child(node,'name').attrs.val;const c=color(child(node,'color'));if(c)f.color=c;return f;}
function readStyles(node){if(!node)return{styles:[{}],dxfs:[]};const formats={...builtins};for(const n of descendants(node,'numFmt'))formats[n.attrs.numFmtId]=n.attrs.formatCode;const fonts=children(child(node,'fonts'),'font').map(readFont),fills=children(child(node,'fills'),'fill').map(n=>color(child(child(n,'patternFill'),'fgColor'))),borders=children(child(node,'borders'),'border').map(n=>{const edge=n.children.find(c=>c.attrs.style);return edge?{color:color(child(edge,'color'))??'#82998a',width:1}:undefined;});const styles=children(child(node,'cellXfs'),'xf').map(n=>{const s={font:fonts[+n.attrs.fontId]??{},numberFormat:formats[n.attrs.numFmtId]??'General'},a=child(n,'alignment');if(fills[+n.attrs.fillId])s.fill=fills[+n.attrs.fillId];if(borders[+n.attrs.borderId])s.border=borders[+n.attrs.borderId];if(a){if(a.attrs.horizontal&&a.attrs.horizontal!=='general')s.horizontalAlignment=a.attrs.horizontal;if(a.attrs.vertical)s.verticalAlignment=a.attrs.vertical;s.wrapText=a.attrs.wrapText==='1';}if(child(n,'protection')?.attrs.locked==='0')s.locked=false;return s;});const dxfs=children(child(node,'dxfs'),'dxf').map(n=>({font:readFont(child(n,'font')),fill:color(child(child(child(n,'fill'),'patternFill'),'fgColor'))}));return{styles:styles.length?styles:[{}],dxfs};}
/** Imports the supported OOXML subset. Warnings explicitly identify discarded feature families. */
export async function importXlsx(input){
  const files=await readZip(input),decoder=new TextDecoder('utf-8',{fatal:true}),warnings=[];
  const read=path=>files.has(path)?parseXML(decoder.decode(files.get(path))):null;
  const rels=path=>new Map(children(read(relPath(path)),'Relationship').map(r=>[r.attrs.Id,{...r.attrs,path:normalizePath(path,r.attrs.Target)}]));
  const rootRelationships=children(read('_rels/.rels'),'Relationship'),wbRel=rootRelationships.find(r=>r.attrs.Type?.endsWith('/officeDocument'));
  const wbPath=wbRel?wbRel.attrs.Target.replace(/^\//,''):'xl/workbook.xml',root=read(wbPath);if(!root)throw new Error('Workbook part not found');if(['1','true'].includes(child(root,'workbookPr')?.attrs.date1904))throw new Error('The 1904 date system is not yet supported; convert the workbook to the 1900 date system before importing.');
  const references=rels(wbPath),stylePath=[...references.values()].find(r=>r.Type.endsWith('/styles'))?.path??'xl/styles.xml',{styles,dxfs}=readStyles(read(stylePath));
  const stringsPath=[...references.values()].find(r=>r.Type.endsWith('/sharedStrings'))?.path??'xl/sharedStrings.xml',strings=children(read(stringsPath),'si').map(si=>descendants(si,'t').map(allText).join(''));
  const snapshot={format:'GridWeb',version:1,name:'Imported workbook',locale:'en-US',sheets:[],names:[]};let count=0;
  for(const [si,item]of children(child(root,'sheets'),'sheet').entries()){
    if(snapshot.sheets.length>=256)throw new RangeError('Worksheet limit');const ref=references.get(item.attrs['r:id']);if(!ref||ref.TargetMode==='External')throw new Error('Invalid worksheet relationship');const doc=read(ref.path);if(!doc||doc.name!=='worksheet'){warnings.push(`Skipped unsupported sheet ${item.attrs.name}.`);continue;}
    const sheet={id:'sheet-'+si,name:item.attrs.name,cells:[],meta:{rows:{},columns:{},merges:[],tables:[],charts:[],validations:[],conditionalFormats:[]}},cells=descendants(child(doc,'sheetData'),'c'),masters=new Map(),arrays=[];
    for(const n of cells){const f=child(n,'f');if(f?.attrs.t==='shared'&&f.text)masters.set(f.attrs.si,{address:n.attrs.r,formula:'='+f.text});if(f?.attrs.t==='array'&&f.attrs.ref)arrays.push({anchor:n.attrs.r,range:parseRange(f.attrs.ref)});}
    for(const n of cells){if(++count>MAX_OPERATION_CELLS)throw new RangeError('Import exceeds 250,000 stored cells');const p=parseCell(n.attrs.r),f=child(n,'f'),v=child(n,'v')?.text??'',type=n.attrs.t,record={input:null,literal:false,style:styles[+n.attrs.s||0]??{}};
      if(f){let formula=f.text;if(f.attrs.t==='shared'&&!formula){const base=masters.get(f.attrs.si);if(!base)throw new Error('Shared formula master not found');const bp=parseCell(base.address);formula=shiftFormula(base.formula,p.row-bp.row,p.column-bp.column).slice(1);}record.input='='+formula;}
      else if(type==='s'){if(!/^\d+$/.test(v)||+v>=strings.length)throw new Error('Invalid shared-string index');record.input=strings[+v];record.literal=true;}
      else if(type==='inlineStr'){record.input=descendants(child(n,'is'),'t').map(allText).join('');record.literal=true;}
      else if(type==='str'){record.input=v;record.literal=true;}
      else if(type==='b')record.input=v==='1';else if(type==='e')record.input={error:/^#/.test(v)?v:'#VALUE!'};
      else if(type==='d'){const date=new Date(v);if(!Number.isFinite(date.getTime()))throw new Error('Invalid ISO date');record.input=(date.getTime()-Date.UTC(1899,11,30))/86400000;record.style={...record.style,numberFormat:record.style.numberFormat==='General'?'yyyy-mm-dd':record.style.numberFormat};}
      else if(v!==''){record.input=Number(v);if(!Number.isFinite(record.input))throw new Error('Invalid numeric cell');}
      if(!f&&arrays.some(a=>a.anchor!==n.attrs.r&&p.row>=a.range.r1&&p.row<=a.range.r2&&p.column>=a.range.c1&&p.column<=a.range.c2))record.input=null;
      sheet.cells.push([p.row*MAX_COLUMNS+p.column,record]);
    }
    for(const n of children(child(doc,'sheetData'),'row'))if(n.attrs.ht||n.attrs.hidden||n.attrs.outlineLevel)sheet.meta.rows[+n.attrs.r-1]={size:n.attrs.ht?+n.attrs.ht/0.75:24,hidden:n.attrs.hidden==='1',outline:+n.attrs.outlineLevel||0};
    for(const n of descendants(child(doc,'cols'),'col')){const min=+n.attrs.min,max=+n.attrs.max;if(min<1||max>MAX_COLUMNS||max<min)throw new Error('Invalid column range');for(let c=min;c<=max;c++)sheet.meta.columns[c-1]={size:n.attrs.width?+n.attrs.width*7+5:100,hidden:n.attrs.hidden==='1'};}
    sheet.meta.merges=descendants(doc,'mergeCell').map(n=>parseRange(n.attrs.ref));const pane=descendants(doc,'pane')[0];if(pane?.attrs.state==='frozen'||pane?.attrs.state==='frozenSplit'){sheet.meta.freezeRows=+pane.attrs.ySplit||0;sheet.meta.freezeColumns=+pane.attrs.xSplit||0;}
    sheet.meta.protected=!!child(doc,'sheetProtection');const page=child(doc,'pageSetup');sheet.meta.print={paper:page?.attrs.paperSize==='1'?'Letter':'A4',orientation:page?.attrs.orientation??'portrait',scale:(+page?.attrs.scale||100)/100,repeatRows:0};
    const filter=child(doc,'autoFilter');if(filter){const criteria=[];for(const c of children(filter,'filterColumn')){const f=descendants(c,'filter')[0]??descendants(c,'customFilter')[0];if(f){const prefix={equal:'',notEqual:'<>',greaterThan:'>',lessThan:'<',greaterThanOrEqual:'>=',lessThanOrEqual:'<='}[f.attrs.operator??'equal']??'';criteria.push({column:+c.attrs.colId,value:prefix+f.attrs.val});}}sheet.meta.filter={range:parseRange(filter.attrs.ref),criteria};}
    for(const n of descendants(doc,'dataValidation')){
      const type={list:'list',decimal:'number',whole:'whole',date:'date',textLength:'textLength',custom:'custom'}[n.attrs.type];if(!type){warnings.push('An unsupported validation rule was skipped.');continue;}for(const address of(n.attrs.sqref??'').split(/\s+/).filter(Boolean)){const rule={type,range:parseRange(address),allowBlank:n.attrs.allowBlank!=='0',message:n.attrs.error};const a=child(n,'formula1')?.text??'',b=child(n,'formula2')?.text??'';if(type==='list'){if(!a.startsWith('"')){warnings.push('Range-based validation list skipped; use a literal list.');continue;}rule.values=a.replace(/^"|"$/g,'').split(',');}else if(type==='custom')rule.formula='='+a;else{if(n.attrs.operator==='lessThanOrEqual')rule.max=Number(a);else{if(a!=='')rule.min=Number(a);if(b!=='')rule.max=Number(b);}}sheet.meta.validations.push(rule);}
    }
    for(const block of children(doc,'conditionalFormatting'))for(const address of(block.attrs.sqref??'').split(/\s+/).filter(Boolean))for(const n of children(block,'cfRule')){
      const rule={range:parseRange(address),style:dxfs[+n.attrs.dxfId]??{}};
      if(n.attrs.type==='dataBar'){rule.type='dataBar';rule.color=color(descendants(n,'color')[0]);}else if(n.attrs.type==='colorScale'){rule.type='colorScale';const colors=descendants(n,'color');rule.minColor=color(colors[0]);rule.maxColor=color(colors.at(-1));}else if(n.attrs.type==='expression'){rule.type='formula';rule.formula='='+(child(n,'formula')?.text??'FALSE');}else if(n.attrs.type==='duplicateValues')rule.type='duplicate';else if(n.attrs.type==='cellIs'){rule.type='cellValue';const op={equal:'=',notEqual:'<>',greaterThan:'>',lessThan:'<',greaterThanOrEqual:'>=',lessThanOrEqual:'<='}[n.attrs.operator];if(!op){warnings.push('Unsupported conditional comparison skipped.');continue;}rule.operator=n.attrs.operator;const raw=child(n,'formula')?.text??'0';rule.value=/^"/.test(raw)?raw.slice(1,-1).replace(/""/g,'"'):Number.isFinite(Number(raw))?Number(raw):raw;rule.criteria=op+String(rule.value);}else{warnings.push('Unsupported conditional formatting rule skipped.');continue;}sheet.meta.conditionalFormats.push(rule);
    }
    const sr=rels(ref.path);
    for(const t of descendants(doc,'tablePart')){const tr=sr.get(t.attrs['r:id']),table=tr&&read(tr.path);if(table)sheet.meta.tables.push({name:table.attrs.displayName??table.attrs.name,range:parseRange(table.attrs.ref),style:'green'});}
    for(const r of sr.values())if(r.Type.endsWith('/comments')){const comments=read(r.path);for(const c of descendants(comments,'comment')){const p=parseCell(c.attrs.ref),n=p.row*MAX_COLUMNS+p.column;let pair=sheet.cells.find(([k])=>k===n);if(!pair){pair=[n,{input:null,style:{}}];sheet.cells.push(pair);}pair[1].comment=descendants(c,'t').map(allText).join('');}}
    for(const r of sr.values())if(r.Type.endsWith('/drawing')){
      const drawing=read(r.path),dr=rels(r.path);for(const anchor of drawing?.children??[]){const refNode=descendants(anchor,'chart')[0],cr=refNode&&dr.get(refNode.attrs['r:id']);if(!cr)continue;const doc=read(cr.path),plot=descendants(doc,'plotArea')[0],kind=plot?.children.find(n=>['barChart','lineChart','areaChart','pieChart','scatterChart'].includes(n.name));if(!kind){warnings.push('Unsupported chart family skipped.');continue;}
        const series=children(kind,'ser'),cat=descendants(child(series[0],'cat')??child(series[0],'xVal'),'f')[0]?.text,vals=series.map(s=>descendants(child(s,'val')??child(s,'yVal'),'f')[0]?.text).filter(Boolean);if(!cat||!vals.length){warnings.push('Chart with literal or unsupported data references skipped.');continue;}
        try{const ranges=[parseRange(cat),...vals.map(parseRange)];if(ranges.some(r=>r.sheet&&r.sheet!==sheet.name)){warnings.push('Cross-worksheet chart references skipped.');continue;}const from=child(anchor,'from'),ext=child(anchor,'ext'),to=child(anchor,'to');const row=+(child(from,'row')?.text??0),column=+(child(from,'col')?.text??0);sheet.meta.charts.push({id:'chart-'+sheet.meta.charts.length,title:descendants(descendants(doc,'title')[0],'t').map(allText).join('')||'Chart',type:kind.name==='barChart'?(child(kind,'barDir')?.attrs.val==='bar'?'bar':'column'):kind.name.replace('Chart',''),range:{r1:Math.max(0,Math.min(...ranges.map(r=>r.r1))-1),c1:Math.min(...ranges.map(r=>r.c1)),r2:Math.max(...ranges.map(r=>r.r2)),c2:Math.max(...ranges.map(r=>r.c2))},row,column,width:ext?+ext.attrs.cx/9525:Math.max(200,(+(child(to,'col')?.text??column+5)-column)*100),height:ext?+ext.attrs.cy/9525:Math.max(150,(+(child(to,'row')?.text??row+12)-row)*24)});}catch{warnings.push('A chart range could not be imported.');}
      }
    }
    snapshot.sheets.push(sheet);
  }
  for(const n of descendants(child(root,'definedNames'),'definedName')){const sheet=snapshot.sheets[+n.attrs.localSheetId];if(n.attrs.name==='_xlnm.Print_Area'){if(sheet)try{sheet.meta.print.area=parseRange(n.text);}catch{warnings.push('Multiple print areas are not supported.');}}else if(n.attrs.name==='_xlnm.Print_Titles'){const m=/\$?(\d+):\$?(\d+)/.exec(n.text);if(sheet&&m)sheet.meta.print.repeatRows=+m[2]-+m[1]+1;}else if(!n.attrs.name.startsWith('_xlnm.'))snapshot.names.push([n.attrs.name,'='+n.text]);}
  const active=+descendants(root,'workbookView')[0]?.attrs.activeTab||0;snapshot.activeSheet=snapshot.sheets[active]?.id;
  for(const[path]of files)if(/(?:vbaProject\.bin|externalLinks\/|pivotTables\/|connections\.xml|queryTables\/|slicer|threadedComment|media\/)/i.test(path))warnings.push('Not imported: '+path);
  if(!snapshot.sheets.length)throw new Error('No supported worksheets');const workbook=Workbook.FromJSON(snapshot);
  const unsupported=new Set();for(const s of workbook._sheets)for(const n of s._formulaCells){const v=s.GetCell(Math.floor(n/MAX_COLUMNS),n%MAX_COLUMNS).Value;if(isError(v)&&v.code==='#NAME?')unsupported.add(v.detail);}warnings.push(...unsupported);
  return{workbook,warnings:[...new Set(warnings)]};
}
