import {Workbook} from './model.js';
import {createHostBridge} from './host.js';
/** Worker entry: exchange {id, method, ...arguments}; no DOM or user-script evaluation. */
export function createWorkerHandler(send){const control={Workbook:new Workbook(),Selection:'A1',Select(address){this.Selection=address;},get Sheet(){return this.Workbook.ActiveWorksheet;},set Sheet(value){this.Workbook.ActiveWorksheet=value;}};const bridge=createHostBridge(control,{postMessage:json=>send(JSON.parse(json))});return{handle(data){send(JSON.parse(bridge.dispatch(JSON.stringify(data))));},Dispose(){bridge.Dispose();}};}
if(typeof WorkerGlobalScope!=='undefined'&&globalThis instanceof WorkerGlobalScope){const handler=createWorkerHandler(message=>postMessage(message));addEventListener('message',event=>handler.handle(event.data));}
/** Owns pending calls, timeouts and cancellation; the worker is supplied by the host. */
export class WorkbookWorkerClient{
 constructor(worker,{timeout=30000}={}){this.Worker=worker;this.Timeout=timeout;this._pending=new Map();this._next=0;this._disposed=false;this._onMessage=e=>{const item=this._pending.get(e.data?.id);if(!item)return;this._pending.delete(e.data.id);item.cleanup();e.data.error?item.reject(new Error(e.data.error.message)):item.resolve(e.data.result);};worker.addEventListener('message',this._onMessage);}
 Call(method,args={},signal){if(this._disposed)return Promise.reject(new Error('Worker client disposed'));if(signal?.aborted)return Promise.reject(signal.reason??new Error('Canceled'));const id=++this._next;return new Promise((resolve,reject)=>{const abort=()=>{this._pending.delete(id);cleanup();reject(signal.reason??new Error('Canceled'));};const timer=setTimeout(()=>{this._pending.delete(id);cleanup();reject(new Error('Worker request timed out'));},this.Timeout);const cleanup=()=>{clearTimeout(timer);signal?.removeEventListener('abort',abort);};this._pending.set(id,{resolve,reject,cleanup});signal?.addEventListener('abort',abort,{once:true});try{this.Worker.postMessage({...args,id,method});}catch(e){this._pending.delete(id);cleanup();reject(e);}});}
 Dispose({terminate=false}={}){if(this._disposed)return;this._disposed=true;this.Worker.removeEventListener('message',this._onMessage);for(const p of this._pending.values()){p.cleanup();p.reject(new Error('Worker client disposed'));}this._pending.clear();if(terminate)this.Worker.terminate();}
}
